feat(evm): add gaslimit opcode
kkrt-labs/kakarot-ssj pull request #192
Opened 2023-08-26 13:57 UTC by LucasLvy

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Resolves: #154 

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

2023-08-27 13:09 UTC, Eikix requested changes

2023-08-27 13:09 UTC, Eikix commented on crates/evm/src/context.cairo
> +            gas_limit
can gas limit be part of static context and can you implement a getter?

2023-08-28 16:36 UTC, enitrat submitted a review, later dismissed
lgtm

2023-08-28 17:01 UTC, enitrat approved these changes

2023-08-28 17:57 UTC, Eikix approved these changes

2023-08-28 17:57 UTC, merged