feat: implement 0x37 - CALLDATACOPY Opcode
kkrt-labs/kakarot-ssj pull request #197
Opened 2023-08-27 07:52 UTC by khaeljy

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Resolves: #123

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

2023-08-27 13:38 UTC, Eikix reviewed
Hey! Welcome, great first pr 🦾
Can we check if we can use slice instead of looping and copying?

2023-08-27 13:38 UTC, Eikix commented on crates/evm/src/instructions/environmental_information.cairo
> +        let mut i: u32 = 0;
can we instead use logic that resembles slice? 
do we have a slice util we can use here?

2023-08-27 13:44 UTC, Eikix commented on crates/evm/src/instructions/environmental_information.cairo
> +        let destOffset: u32 = (*popped[0]).try_into().unwrap();
we should handle error cases
if it's possible to implement error type conversion, we can try it out! 
Implementing Into for u32 conversion error into evm
error:)!
and creating a new enum case for evm error here: TypeConversionError

2023-08-27 13:44 UTC, Eikix commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +            assert(*results[i] == 0, 'wrong data value');
ah it's unlucky we can't assert equality for memory and felt dict, we should probably later create test utils for asserting equality @enitrat

2023-08-27 13:44 UTC, Eikix commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +fn test_calldata_copy_with_offset() {
since it's all zeros are we testing properly the offset ?

2023-08-27 13:44 UTC, Eikix commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +    let destOffset: u32 = 32;
why destOffset = 32 every time?

2023-08-27 13:51 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +    let destOffset: u32 = 32;
It's an arbitrary value.

2023-08-27 13:51 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +fn test_calldata_copy_with_offset() {
Well done, I'm going to rewrite this test.

2023-08-27 14:03 UTC, khaeljy commented on crates/evm/src/instructions/environmental_information.cairo
> +        let mut i: u32 = 0;
Oh, I didn't know the slice() function, my bad.
I'll reimplement using this function.

2023-08-27 16:13 UTC, khaeljy commented on crates/evm/src/instructions/environmental_information.cairo
> +        let destOffset: u32 = (*popped[0]).try_into().unwrap();
How we can handle conversion type errors?
Do I need to implement a new utility function (e.g. u256_to_u32) or is there a better way?

2023-08-27 16:33 UTC, Eikix commented on crates/evm/src/instructions/environmental_information.cairo
> +        let destOffset: u32 = (*popped[0]).try_into().unwrap();
Let me ask some Cairo compiler team ppl!

2023-08-27 17:24 UTC, khaeljy commented on crates/evm/src/instructions/environmental_information.cairo
> +        let destOffset: u32 = (*popped[0]).try_into().unwrap();
Oh, I just pushed a version with a new utility function. But, if there's a better way, I'll refactor!

2023-08-28 21:01 UTC, enitrat commented on crates/utils/src/helpers.cairo
> +use evm::errors::{EVMError, TYPE_CONVERSION_ERROR};
@ClementWalter wdyt of having  evm-specific utilities instead. Doing this creates some kind of circular dependency

2023-08-28 21:01 UTC, enitrat commented on crates/evm/src/instructions/environmental_information.cairo
> +        let destOffset: u32 = u256_to_u32(*popped[0])?;
Regarding the other fields, in Geth they're checked when computing gas costs, which returns an error in case of an overflow

https://github.com/ethereum/go-ethereum/blob/fe24d22a622926c024030480773faf83b78b1319/core/vm/gas_table.go#L73-L76

@Eikix I think the question to answer is would be "do we want to revert the whole tx or just the current execution context". if 1. then we can panic directly. otherwise we can return that error

2023-08-28 21:04 UTC, enitrat commented on crates/evm/src/instructions/environmental_information.cairo
> +        let destOffset: u32 = (*popped[0]).try_into().unwrap();
> Implementing Into for u32 conversion error into evm
error:)!

@khaeljy you could implement the `Into` trait for `Into<u256, Result<u32, EVMError>>` for that, which is a bit more idiomatic :)

2023-08-28 21:24 UTC, khaeljy commented on crates/evm/src/instructions/environmental_information.cairo
> +        let destOffset: u32 = (*popped[0]).try_into().unwrap();
Ok, I'll correct it

2023-08-28 21:35 UTC, khaeljy commented on crates/evm/src/instructions/environmental_information.cairo
> +        let mut slice_size = size;
Okay, thanks. I'm not used to this way of doing things.

2023-08-28 21:58 UTC, khaeljy commented on crates/utils/src/helpers.cairo
> +use evm::errors::{EVMError, TYPE_CONVERSION_ERROR};
Perhaps we can add a helpers file to the evm module?

2023-08-28 22:01 UTC, enitrat commented on crates/utils/src/helpers.cairo
> +use evm::errors::{EVMError, TYPE_CONVERSION_ERROR};
yeah that's what we had at first and we reworked the structure of it. Imo evm-specific utils should be in the evm crate. Feel free to do it :)

2023-08-28 23:24 UTC, enitrat reviewed
lgtm, will merge after thinking a bit about the type conversion thing :)

2023-08-28 23:24 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +fn test_calldata_copy(destOffset: u32, offset: u32, mut size: u32) {
```suggestion
fn test_calldata_copy(dest_offset: u32, offset: u32, mut size: u32) {
```

2023-08-28 23:24 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +    ctx.stack.push(destOffset.into());
```suggestion
    ctx.stack.push(dest_offset.into());
```

2023-09-04 11:32 UTC, ClementWalter requested changes

2023-09-04 11:32 UTC, ClementWalter commented on crates/evm/src/instructions/environmental_information.cairo
> +        let call_data: Span<u8> = self.call_context().call_data();
it's `calldata`, not `call_data`. The `CallContext` has been badly named (and merged), but about to be fixed as well (https://github.com/kkrt-labs/kakarot-ssj/issues/269)

2023-09-04 11:32 UTC, ClementWalter commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
>      let call_data: Span<u8> = ctx.call_context().call_data();
it's `calldata`, not `call_data`

2023-09-04 11:32 UTC, ClementWalter commented on crates/evm/src/instructions/environmental_information.cairo
> +            self.memory.store_n(out_of_bounds_bytes.span(), dest_offset + slice_size);
it looks non optimal to do two times `memory.store_n` because this function is quite expensive.

I think that it's cheaper to first pad `data_to_copy`, then to `store_n` only once, @enitrat

2023-09-04 12:34 UTC, enitrat commented on crates/evm/src/instructions/environmental_information.cairo
> +            self.memory.store_n(out_of_bounds_bytes.span(), dest_offset + slice_size);
@ClementWalter `data_to_copy` is a span and can't be padded, the solution would be to clone it into an array and then pad this array, but then I'm not sure it would actually be more effective. I will check and report back

2023-09-04 13:50 UTC, enitrat approved these changes

2023-09-04 13:50 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +    let result: u256 = ctx.memory.load_internal(dest_offset).into();
this assumes that the copied calldata holds in one single u256 value. What if it's bigger? It will be spread in multiple words in that case

2023-09-04 14:19 UTC, enitrat commented
```rust

        if (copied.len() < size) {
            let n_zeroes = size - copied.len();
            self.memory.store_n(copied.pad_end_zeroes(n_zeroes).span(), dest_offset);
        } else {
            self.memory.store_n(copied, dest_offset);
        }
```

looks to be more optimized - I will re-verify once the requested changes have been applied

2023-09-04 17:41 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +    let result: u256 = ctx.memory.load_internal(dest_offset).into();
I worked on it, but it revealed a bug (#275) that's preventing me from continuing.

2023-09-05 10:17 UTC, enitrat commented
> looks to be more optimized - I will re-verify once the requested changes have been applied

Given that this implies cloning an entire memory segment just to pad zeroes, I think there might be a point at which it becomes more expensive to do a clone than it is to call twice store_n. Will research this later in https://github.com/kkrt-labs/kakarot-ssj/issues/278

2023-09-08 08:44 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +fn test_calldata_copy_type_conversion_error() {
change all `calldata_copy` by `calldatacopy`

2023-09-08 08:44 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +    let calldata_len = calldata.len();
use `calldata.len()` everywhere directly

2023-09-08 08:44 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +    let calldata_len = calldata.len();
unused var

2023-09-08 08:44 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +    let calldata_len = calldata.len();
unused var

2023-09-08 08:44 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +
remove intermediate emptylines

2023-09-08 08:44 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +
remove intermediate emptylines

2023-09-08 08:44 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +    let calldata_len = calldata.len();
remove intermediate emptylines

2023-09-08 08:44 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +    let calldata_len = calldata.len();
unused var

2023-09-08 08:44 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +
remove intermediate lines when the actions performed belong to the same group - e.g. declare test variables together, then linebreak before doing a push, then assertions together, etc.

2023-09-08 08:44 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +    loop {
can you add a comment with context here

2023-09-08 08:44 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +        loop {
can you add some context here about what's done in the loop

2023-09-08 08:44 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +        let result: u256 = ctx.memory.load_internal(dest_offset + (i * 32)).into();
why are we not loading a Span<u8> from memory ? Wouldnt it be a lot easier to verify that the output result matches the calldata input padded with zeroes?

2023-09-08 08:44 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +    loop {
I don't understand what's the goal here

2023-09-08 08:54 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +    let calldata_len = calldata.len();
It's not my code, it's not relative to this PR, should I make the fixes in this PR or create a new one?

2023-09-08 08:54 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +
It's not my code, it's not relative to this PR, should I make the fixes in this PR or create a new one?

2023-09-08 08:55 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +    let calldata_len = calldata.len();
It's not my code, it's not relative to this PR, should I make the fixes in this PR or create a new one?

2023-09-08 08:55 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +
It's not my code, it's not relative to this PR, should I make the fixes in this PR or create a new one?

2023-09-08 08:55 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +    let calldata_len = calldata.len();
It's not my code, it's not relative to this PR, should I make the fixes in this PR or create a new one?

2023-09-08 08:55 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +    let calldata_len = calldata.len();
It's not my code, it's not relative to this PR, should I make the fixes in this PR or create a new one?

2023-09-08 08:55 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +
It's not my code, it's not relative to this PR, should I make the fixes in this PR or create a new one?

2023-09-08 09:01 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +    loop {
Memory initialization with a value to verify that if the offset + size is out of the bound bytes, 0's have been copied.
Otherwise, the memory value would be 0, and we wouldn't be able to check it.

2023-09-08 09:06 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +    let calldata_len = calldata.len();
yes please, inside this one

2023-09-08 09:07 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +    loop {
ok, can you add this in a code comment please?

2023-09-08 12:03 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +        let result: u256 = ctx.memory.load_internal(dest_offset + (i * 32)).into();
I tried to load memory with `load_n_internal()` method, but there seems to be a bug.
Awaiting resolution of issue #327

2023-09-08 19:45 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +        let result: u256 = ctx.memory.load_internal(dest_offset + (i * 32)).into();
Thanks, it's so much simpler...

2023-09-08 19:46 UTC, khaeljy commented
Tests will be fixed after merge PR https://github.com/kkrt-labs/kakarot-ssj/pull/331

2023-09-08 20:01 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +    test_calldatacopy(32, 2, 0);
is this really testing something if the size is 0? Apart from the fact that the copied array is empty

2023-09-08 20:12 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +    // For out of bound bytes, 0s will be copied.
Make sense...

2023-09-08 20:18 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +    test_calldatacopy(32, 2, 0);
If `size == 0`, `size` is set to `calldata.len() - offset` in `test_calldatacopy` function.
Your comment makes me think it's misleading, so I'll clarify it.

2023-09-08 20:20 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +    test_calldatacopy(32, 2, 0);
thanks!

2023-09-08 20:24 UTC, enitrat reviewed
Looks good now ! Waiting for bugfix PR merge to finish. Sorry it was a bit long but it was the first PR you opened, now it's going to be easier 💪

2023-09-11 10:39 UTC, enitrat approved these changes
💯

2023-09-11 11:22 UTC, merged