feat: implement 0x15 - ISZERO opcode
kkrt-labs/kakarot-ssj pull request #232
Opened 2023-08-30 01:20 UTC by Noeljarillo

Implemented the OP code iszero

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

2023-08-30 18:29 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_comparison_operations.cairo
> +fn test_is_zero() {
```suggestion
fn test_is_zero_true() {
```

Can you also add another test 


`test_is_zero_false`

2023-08-30 18:29 UTC, enitrat commented on crates/evm/src/instructions/comparison_operations.cairo
> +        let popped = self.stack.pop_n(1)?;
```suggestion
        let popped = self.stack.pop()?;
```

2023-09-03 14:43 UTC, Noeljarillo commented on crates/evm/src/tests/test_instructions/test_comparison_operations.cairo
> +fn test_is_zero() {
got it working on it now!

2023-09-03 18:48 UTC, Noeljarillo reviewed
added suggested change, and false test case

2023-09-04 10:04 UTC, ClementWalter requested changes
I think that you need to format as well

2023-09-04 10:04 UTC, ClementWalter commented on crates/evm/src/tests/test_instructions/test_comparison_operations.cairo
> +    assert(ctx.stack.peek().unwrap() == 0x01, 'stack top should be 0x01');
can you put a more meaningful error message, like "stack top should be true" instead?

2023-09-04 10:04 UTC, ClementWalter commented on crates/evm/src/tests/test_instructions/test_comparison_operations.cairo
> +    assert(ctx.stack.peek().unwrap() == 0x00, 'stack top should be 0x00');
same here, with "false" plz

2023-09-05 07:15 UTC, enitrat approved these changes
LGtM!

2023-09-05 07:15 UTC, enitrat approved these changes

2023-09-05 10:28 UTC, ClementWalter approved these changes

2023-09-05 10:29 UTC, merged