feat: implement PC opcode
kkrt-labs/kakarot-ssj pull request #264
Opened 2023-09-02 15:10 UTC by lambda-0x

## Pull Request type

Please check the type of change your PR introduces:

- [x] Feature

## What is the current behavior?

Resolves: #254 

## What is the new behavior?

- implements `PC` opcode

## Does this introduce a breaking change?

- [x] No

2023-09-02 15:41 UTC, lambda-0x commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +
i am not sure if it would be a good idea to add a test for each instruction manually, instead we can make sure that each instruction is updating the PC as expected. 

both kakarot in cairo 0 and geth doesn't seem it test PC opcode manually.

2023-09-02 16:02 UTC, lambda-0x commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +
we need to call `decode_and_execute` with proper context to actually update the PC, any ideas on how to test all the cases cleanly?

2023-09-02 19:06 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +
Maybe wait until issue #250 is implemented, but that wouldn't really be a unit test...

2023-09-02 19:32 UTC, lambda-0x commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +
i am not sure how that would be useful here?

2023-09-02 19:38 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +
You can execute JUMP to a given index, and then you can check whether the new PC has the right value.

2023-09-02 19:40 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +
Or simply use `ctx.program_counter = GIVEN_INDEX`

2023-09-02 19:48 UTC, lambda-0x commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +
what would that be testing though? 

the point of testing is that you have an `initial setup` -> `do some processing` -> `assert on the resulting` state.

If we set PC manually it won't test that running an instruction produces correct PC (maybe checking for correctness maybe out of scope of this PR but i just wanted to point that out)

2023-09-02 19:50 UTC, lambda-0x commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +
does this PR needs to check that all opcodes results in a proper PC value?

cc: @enitrat @Eikix

2023-09-02 19:58 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +
ah ok sorry, I didn't quite get your point.

2023-09-04 09:16 UTC, ClementWalter commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +
there is actually a test in kakarot 0, see `test__exec_pc__should_update_after_incrementing`

regarding what to test from a unit testing perspective:
- the `exec_pc` opcode is supposed to put whatever the PC value is in the Stack, so setting the PC to something and asserting that the stack got the same value is fine
- the `exec_pc` is not responsible for actually incrementing the PC, so we shall not test that PC is incremented properly in a PC unit test
- as you pointed out, `decode_and_execute` is responsible for incrementing the PC, and asserting this increment is done properly will be done in a `decode_and_execute` test

2023-09-04 09:19 UTC, ClementWalter requested changes
please just do the same test as in kakarot (see https://github.com/ClementWalter/kakarot/blob/b6619adb6092984f4c6b4fa512ebf07ec8d47299/tests/src/kakarot/instructions/test_memory_operations.cairo#L20).

ie put a value and test that PC returns it, for several values

2023-09-04 10:31 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +
can you add an inlined `set_pc` method to the 
 `ExecutionContext` struct implementation, and manually set this value in the test to assert that the value popped is not 0 (default value)

2023-09-04 10:31 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +
agreed with clement

2023-09-04 10:44 UTC, lambda-0x commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +
i thought because we where setting the value manually the test doesn't make much sense, but yeah when you think about that way it make sense. will add.

2023-09-04 11:01 UTC, lambda-0x commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +
done

2023-09-04 11:33 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +fn test_pc_gets_updated_properly_2() {
only 1 test of this kind is enough

2023-09-04 11:44 UTC, ClementWalter commented
> only 1 test of this kind is enough 

we dramatically miss a way to parametrize the tests, in cairo0 we had tests for PC in `range(1, 15)`

2023-09-04 11:51 UTC, enitrat commented
> we dramatically miss a way to parametrize the tests, in cairo0 we had tests for PC in range(1, 15)

Agreed but here the logic is fairly simple and doesn't present any other edge cases than pc > range bound. I wouldn't duplicate test for no reason

2023-09-04 11:57 UTC, lambda-0x commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +fn test_pc_gets_updated_properly_2() {
thought so but because clement told to test few cases, i added it anyway.

2023-09-04 11:58 UTC, enitrat approved these changes
lgtm

2023-09-05 09:30 UTC, ClementWalter approved these changes

2023-09-05 09:31 UTC, merged