feat: implement the test suite for MLOAD opcode
kkrt-labs/kakarot-ssj pull request #265
Opened 2023-09-02 15:29 UTC by khaeljy

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Resolves: #245

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2023-09-02 15:32 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +        // This is the test case in kakarot cairo0, but playground say, the memory size should be 64 ???
I'm not sure about the expected memory size, the test in kakarot cairo0 and evm.codes playground don't say the same thing.

2023-09-02 15:33 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +            16 + 32
I'm not sure about the expected memory size, the test in kakarot cairo0 and evm.codes playground don't say the same thing.

2023-09-02 17:53 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +            16 + 32
The memory load() function seems to add 32 to the offset.

```
fn load(ref self: Memory, offset: usize) -> (u256, usize) {
        let gas_cost = self.ensure_length(32 + offset);
        let loaded_element = self.load_internal(offset);
        (loaded_element, gas_cost)
    }
```

2023-09-02 18:42 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +            16 + 32
This playground seems confirm that the `MSIZE` isn't `offset + 32` but `(offset % 32) * (32 + 1)`

https://www.evm.codes/playground?fork=shanghai&unit=Wei&codeType=Mnemonic&code='%2F%2F%20Put%20the%20state%20in%20memoryw32%200xppppplFFq0zMSTOREvzq1zMLOADv'~lllz%5CnwzPUSHvzzMSIZEqw1%20p~~l00%01lpqvwz~_

2023-09-04 08:53 UTC, ClementWalter commented on crates/evm/src/instructions/memory_operations.cairo
> +        panic_with_felt252('MLOAD not implement yet')
why not panicking for all the non implemented opcode?

2023-09-04 08:57 UTC, ClementWalter commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +    loop {
don't do a loop in a test to test several different cases, write one test per case, or use fixtures if there are the same body

2023-09-04 09:07 UTC, ClementWalter requested changes
Please write one test per case, and put them the same name as they add in cairo 0

2023-09-04 11:44 UTC, enitrat commented on crates/evm/src/instructions/memory_operations.cairo
> +        panic_with_felt252('MLOAD not implement yet')
I think it's just because he added the test and verifies that it panis until it's implemented

2023-09-04 11:44 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +        (0x0000000000000000000000000000000000000000000000000000000000000001, 0, 0x1, 32),
> 0x0000000000000000000000000000000000000000000000000000000000000001

why so many zeroes, it's just the value 1, you can just use `0x1` or simply `1`

2023-09-04 11:44 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +            16 + 32
normally expected memory size is always a multiple of 32

2023-09-04 11:44 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +            16 + 32
> The memory load() function seems to add 32 to the offset.

Memory expansion is performed in `expand` which only increments modulo 32

2023-09-04 11:44 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +    loop {
Let's do this if n_test is <5, otherwise, let's keep it data & loop-based (e.g. other geth tests with n>10 test cases can stay as is

2023-09-04 12:06 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +            16 + 32
Yes, i'm totally agree with you, but this is not what is tested in Kakarot cairo0.
In kakarot cairo0, the test is ` test_offset + 32` ([cf](https://github.com/kkrt-labs/kakarot/blob/b6619adb6092984f4c6b4fa512ebf07ec8d47299/tests/src/kakarot/instructions/test_memory_operations.cairo#L131C38-L131C50))

2023-09-04 12:07 UTC, khaeljy commented on crates/evm/src/instructions/memory_operations.cairo
> +        panic_with_felt252('MLOAD not implement yet')
Yes, I've implemented it only on the function I want to test.

2023-09-04 12:09 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +            16 + 32
> I see actually 3 tests in `kakarot`
> 
> ```
> test__exec_mload_should_load_a_value_from_memory
> test__exec_mload_should_load_a_value_from_memory_with_memory_expansion
> test__exec_mload_should_load_a_value_from_memory_with_offset_larger_than_msize
> ```
> 
> which one are you talking about there?

This one : [test__exec_mload_should_load_a_value_from_memory_with_memory_expansion](https://github.com/kkrt-labs/kakarot/blob/b6619adb6092984f4c6b4fa512ebf07ec8d47299/tests/src/kakarot/instructions/test_memory_operations.cairo#L131C38-L131C50)

2023-09-04 12:23 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +            16 + 32
This seems wrong then 🤔 Ideally I would like contributors to not look at the KKT0 codebase, at least not before finishing writing the cairo 1 behavior, because there might be some errors in the KKT0 codebase and we should not assume that it is correct and blindly reproduce the behavior. The Cairo1 implementation and tests should only be derived from the EVM specification

2023-09-04 21:18 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +            16 + 32
The issue specifies that geth, evm.codes and KKT0 tests must be retrieved. Since we have 3 sets of tests from 3 different sources, I think, on the contrary, that this helps to highlight bugs that might be present in KKT0.

2023-09-05 07:19 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +            16 + 32
> that this helps to highlight bugs that might be present in KKT0.

Definitely, but the goal here is to spot bugs in KKT0, not reproduce them in SSJ! And if you look at the implementation in KKT0 you might have bias when working on the SSJ one

2023-09-05 07:20 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +            16 + 32
I see what you mean, but unfortunately we shouldn't blindly trust it

2023-09-05 07:32 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +            16 + 32
I see, and I agree with you.
We should therefore modify the issues to remove the task: `Create the test suite for MLOAD, taking Kakarot cairo0 examples`

2023-09-05 08:05 UTC, ClementWalter commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +fn assert_mload(memory_value: u256, input: u256, expected_value: u256, expected_memory_size: u32) {
can we stick to the MLOAD semantic? meaning renaming `memory_value` to `value` and `input` to `offset`

2023-09-05 08:20 UTC, ClementWalter commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +            16 + 32
just for the record if anyone pass by, just try on the playground

```
PUSH i
MLOAD
```

and memory size is
- i = 0 => 32
- i = 16 => 64
- i = 684 => 736

2023-09-06 12:05 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +    ctx.stack.push(output);
what is output? do you mean `offset`?

2023-09-06 15:29 UTC, khaeljy commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +    ctx.stack.push(output);
It's a bad copy / paste, I change it!

2023-09-08 11:07 UTC, enitrat commented
Moving discussion and review to #266

2023-09-08 11:07 UTC, closed without merging