feat: implement 0x13 - SGT Opcode
kkrt-labs/kakarot-ssj pull request #271
Opened 2023-09-04 14:19 UTC by TAdev0

## Pull Request type

Please check the type of change your PR introduces:

- Feature

## What is the current behavior?

Resolves: #8 

## What is the new behavior?

Implementation of SGT EVM opcode

## Does this introduce a breaking change?

- No

2023-09-04 14:35 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_comparison_operations.cairo
> +        0x0000000000000000000000000000000000000000000000000000000000000000,
it would be nice to replace all `0x000...1` by `0x1 ` and all `0x000..00` by `0x0`

2023-09-04 14:35 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_comparison_operations.cairo
> +    ctx.stack.push(a).unwrap();
extremely misleading to push `a` before `b` here, when in the implementation `a` is stack[0] (top) and `b` is stack[1]. 

It would be much better if you renamed these parameters

2023-09-04 14:49 UTC, ClementWalter requested changes

2023-09-04 14:49 UTC, ClementWalter commented on crates/evm/src/tests/test_instructions/test_comparison_operations.cairo
> +    ctx.stack.push(a).unwrap();
why `unwrap()` here?

2023-09-04 14:49 UTC, ClementWalter commented on crates/utils/src/u256_signed_math.cairo
> +        let self_positive = self.high < TWO_POW_127;
can't we just use `SignedPartialOrd::slt(other, self)`?

2023-09-04 14:49 UTC, ClementWalter commented on crates/utils/src/u256_signed_math.cairo
> +        let self_positive = self.high < TWO_POW_127;
also, `#[inline]`, and `slt` as well

2023-09-04 14:56 UTC, TAdev0 commented on crates/evm/src/tests/test_instructions/test_comparison_operations.cairo
> +    ctx.stack.push(a).unwrap();
copied SLT style already validated in main , but didn't really understand why... should have asked before.

2023-09-04 14:56 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_comparison_operations.cairo
> +    ctx.stack.push(a).unwrap();
> actually, positive integers ares all values of the uint256 starting from TWO_POW_127, right

Not exactly, positive integers are values starting from `2**255 -1`, which is`0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`. But since the low part is always 2**128-1 we can just check that the high part is under `2**127`

2023-09-04 15:01 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_comparison_operations.cairo
> +    ctx.stack.push(a).unwrap();
>  it also pushes a and b in the wrong order

It's not that they're pushed in the wrong order, it's just that they have the wrong name if we want to respect naming from the implementation. 

when you do `assert_slt(0,1,1)`, you're actually checking whether `1<0`, which is false, so the expected result is correct. I think the misleading part is that you expect parameters to be in the same order as the `slt` function so `1.slt(0)` is false, but the input to `assert_slt` is the order in which values are pushed to the stack.

2023-09-04 15:07 UTC, TAdev0 commented on crates/evm/src/tests/test_instructions/test_comparison_operations.cairo
> +    ctx.stack.push(a).unwrap();
understood ! thank you so much

2023-09-04 15:21 UTC, TAdev0 commented on crates/utils/src/u256_signed_math.cairo
> +        let self_positive = self.high < TWO_POW_127;
thanks for the quick answer. 
what do you mean by  ```#[inline]```? 

Yes ican use ```fn slt```for SGT implementation !

2023-09-04 15:26 UTC, enitrat commented on crates/utils/src/u256_signed_math.cairo
> +        let self_positive = self.high < TWO_POW_127;
when you annotate a function with `#[inline(always)]`, the code of the function will be inlined in the functions that call this function, meaning that the code will be executed directly without a `call` to invoke a specific function. In some cases, it's a better option since it can increase performances, but we have to be careful because it can also drastically increase code size.

2023-09-04 15:26 UTC, enitrat commented on crates/utils/src/u256_signed_math.cairo
> +        let self_positive = self.high < TWO_POW_127;
https://en.wikipedia.org/wiki/Inline_expansion

2023-09-04 15:29 UTC, enitrat commented on crates/utils/src/u256_signed_math.cairo
> -    fn sgt(self: u256, other: u256) -> bool {
no, instead of deleting this function, what you should do is

```rust
fn sgt(self: u256, other: u256) -> bool {
    SignedPartialOrd::slt(other,self)
}
```

2023-09-04 15:29 UTC, enitrat commented on crates/utils/src/u256_signed_math.cairo
>      fn slt(self: T, other: T) -> bool;
and above this line you can add the `#[inline(always)]` attribute. Also above `fn sgt`

2023-09-04 15:30 UTC, TAdev0 commented on crates/utils/src/u256_signed_math.cairo
> +        let self_positive = self.high < TWO_POW_127;
thank you. i'll add it to SLT and SGT. 

do you want me to rename SLT like this?

```
fn assert_slt(b: u256, a: u256, expected: u256) {
    // Given
    let mut ctx = setup_execution_context();
    ctx.stack.push(b);
    ctx.stack.push(a);
```

2023-09-04 15:47 UTC, TAdev0 commented
@enitrat  everything should be ok

2023-09-04 15:57 UTC, enitrat commented on crates/utils/src/u256_signed_math.cairo
>      }
add empty line here between functions

2023-09-04 16:01 UTC, TAdev0 commented on crates/utils/src/u256_signed_math.cairo
>      }
done

2023-09-05 07:50 UTC, ClementWalter approved these changes

2023-09-05 07:51 UTC, merged