fix: store_aligned_words slice
kkrt-labs/kakarot-ssj pull request #273
Opened 2023-09-04 14:51 UTC by enitrat

## Pull Request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Resolves: #270 

## What is the new behavior?

- Array is now moved 16 elements further instead of staying the same
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2023-09-05 07:45 UTC, ClementWalter commented on crates/evm/src/memory.cairo
> +            elements = elements.slice(16, elements.len() - 16);
isn't this more expensive that just incrementing a start index in the loop?

2023-09-05 07:45 UTC, ClementWalter requested changes
isn't there any test to update? if no, a test to add I guess!

2023-09-05 08:45 UTC, enitrat commented on crates/evm/src/memory.cairo
> +            elements = elements.slice(16, elements.len() - 16);
it's slightly better this way

2023-09-06 09:17 UTC, Eikix commented on crates/evm/src/tests/test_memory.cairo
> +    let bytes_arr = array![
should we have a util that inserts sequentially elements inside an array? 
pseudo-code:
```
fill_array_from_to(start: T, end: T) -> array<T>
```

might need to take oneable and add trait logic from herodotus

can be in a separate PR if you think its worth

2023-09-06 10:30 UTC, enitrat commented on crates/evm/src/tests/test_memory.cairo
> +    let bytes_arr = array![
I don't see a usage in multiple places for now, let's open a PR later if it becomes required

2023-09-06 16:43 UTC, enitrat commented
@ClementWalter can you re-approve pls

2023-09-07 01:21 UTC, Eikix approved these changes

2023-09-07 10:08 UTC, ClementWalter approved these changes

2023-09-07 10:08 UTC, merged