add msize opcode
kkrt-labs/kakarot-ssj pull request #286
Opened 2023-09-06 09:40 UTC by rkdud007

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Resolves: #256 

## What is the new behavior?

MSIZE OPCODE

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

2023-09-06 09:57 UTC, danilowhk commented on crates/evm/src/instructions/memory_operations.cairo
> +        let len = self.memory.bytes_len;
```suggestion
        let size: u256 = self.memory.bytes_len.into();
```

2023-09-06 10:21 UTC, enitrat commented on crates/evm/src/instructions/memory_operations.cairo
> +        let len = self.memory.bytes_len;
can you add an inlined `size()` method to memory instead?

2023-09-06 10:39 UTC, rkdud007 commented on crates/evm/src/instructions/memory_operations.cairo
> +        let len = self.memory.bytes_len;
fn size(ref self: Memory) -> u256; ?

2023-09-06 11:59 UTC, enitrat commented on crates/evm/src/memory.cairo
> +    fn size(ref self: Memory) -> u256 {
`#[inline(always)]`

2023-09-06 11:59 UTC, enitrat commented on crates/evm/src/memory.cairo
> +    fn size(ref self: Memory) -> u256 {
```suggestion
    fn size(ref self: Memory) -> usize {
```

2023-09-06 11:59 UTC, enitrat commented on crates/evm/src/instructions/memory_operations.cairo
> +        let len = self.memory.bytes_len;
return usize

2023-09-06 12:07 UTC, enitrat commented on crates/evm/src/memory.cairo
> +    }
add an empty line after function pls!

2023-09-06 12:10 UTC, enitrat commented on crates/evm/src/memory.cairo
> +    }
also fmt

2023-09-06 12:29 UTC, enitrat commented on crates/evm/src/memory.cairo
> +        self.bytes_len.into()
```suggestion
        self.bytes_len
```

2023-09-06 12:32 UTC, enitrat commented
can you add the tests here pls

2023-09-10 10:15 UTC, Eikix reviewed
lgtm

2023-09-10 10:15 UTC, Eikix commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +    assert(ctx.stack.pop().unwrap() == 64, 'should 32 bytes after MSTORE');
error message should be 64 bytes

2023-09-11 10:37 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +    ctx.exec_mstore();
I don't like testing `msize` by executing `mstore` before.

I think it would be better instead to directly execute memory functions like `self.memory.store()`. and then check the size.

2023-09-11 11:26 UTC, Eikix commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +    ctx.exec_mstore();
Agreed

2023-09-11 12:06 UTC, Eikix requested changes

2023-09-11 12:06 UTC, Eikix commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +    ctx.memory.store(value, offset);
i don't think you need to use the stack in this case, just add value and offset without using the stack

2023-09-11 12:06 UTC, Eikix commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +    ctx.memory.store(value, offset);
same

2023-09-11 16:31 UTC, merged