feat: implement 0x52 - MSTORE Opcode
kkrt-labs/kakarot-ssj pull request #290
Opened 2023-09-06 13:23 UTC by Quentash

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Resolves: #243 

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

2023-09-06 16:41 UTC, enitrat reviewed
It would be nice to add a tests that loads the entire memory and verifies the state of it. 

For example when you do

```rust
    ctx.stack.push(0xFF00);
    ctx.stack.push(0x01);
```

Then verifying that the memory is 64 bytes long, that the first word is 0xff and the second word is 0. 

You should also add two cases where we have: 
- no offset
- 32-bytes offset

2023-09-06 16:41 UTC, enitrat commented on crates/evm/src/instructions/memory_operations.cairo
> +        let offset: u32 = Into::<u256, Result<u32, EVMError>>::into((self.stack.pop()?))?;
can you use pop_n instead?

2023-09-06 20:24 UTC, Quentash commented on crates/evm/src/instructions/memory_operations.cairo
> +        let offset: u32 = Into::<u256, Result<u32, EVMError>>::into((self.stack.pop()?))?;
I'm now using pop_n as suggested but I noticed that this increase the gas cost of the operation.
Here is with 2 pop() :
```
test evm::tests::test_instructions::test_memory_operations::test_exec_mstore_should_store_only_F_offset_0 ... ok (gas usage est.: 550490)
test evm::tests::test_instructions::test_memory_operations::test_exec_mstore_should_store_0xFF00_offset_1 ... ok (gas usage est.: 580980)
test evm::tests::test_instructions::test_memory_operations::test_exec_mstore_should_store_only_F_offset_1 ... ok (gas usage est.: 869760)
test evm::tests::test_instructions::test_memory_operations::test_exec_mstore_should_store_0xFF00_offset_0x20 ... ok (gas usage est.: 1539140)
test evm::tests::test_instructions::test_memory_operations::test_exec_mstore_should_store_0xFF_offset_1 ... ok (gas usage est.: 1069230)
test evm::tests::test_instructions::test_memory_operations::test_exec_mstore_should_store_1_offset_1 ... ok (gas usage est.: 869760)
```
Here is with pop_n() :
```
test evm::tests::test_instructions::test_memory_operations::test_exec_mstore_should_store_only_F_offset_0 ... ok (gas usage est.: 618740)
test evm::tests::test_instructions::test_memory_operations::test_exec_mstore_should_store_only_F_offset_1 ... ok (gas usage est.: 938010)
test evm::tests::test_instructions::test_memory_operations::test_exec_mstore_should_store_1_offset_1 ... ok (gas usage est.: 938010)
test evm::tests::test_instructions::test_memory_operations::test_exec_mstore_should_store_0xFF_offset_1 ... ok (gas usage est.: 1137480)
test evm::tests::test_instructions::test_memory_operations::test_exec_mstore_should_store_0xFF00_offset_1 ... ok (gas usage est.: 649230)
test evm::tests::test_instructions::test_memory_operations::test_exec_mstore_should_store_0xFF00_offset_0x20 ... ok (gas usage est.: 1607390)
```

This is not a huge difference (~8%) but I felt like mentionning it.

2023-09-06 20:29 UTC, enitrat commented on crates/evm/src/instructions/memory_operations.cairo
> +        let offset: u32 = Into::<u256, Result<u32, EVMError>>::into((self.stack.pop()?))?;
ah, interesting! thanks for letting me know, I will look into it

2023-09-07 09:12 UTC, Quentash commented
Corrected "succeed" into "succeeded".
Used pop_n(2) instea of 2 pop().
Added a test case with offset 0.
Added a test case with offset 32.
Added memory length verification into tests.
Used integer::BoundedInt for max value.

2023-09-07 11:54 UTC, ClementWalter requested changes
thx, there are too much test for this! in terms of unit testing, when writing tests for `exec_{}` we mainly need to test that we popped enough arguments, and that we pass them correctly to the underlying function implementing the logic (if the logic is in another funcion, as it is the case here).

2023-09-07 11:54 UTC, ClementWalter commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +fn test_exec_mstore_should_store_only_F_offset_0() {
`should_store_max_uint256_at_offset_0` as we don't really store "F"

2023-09-07 11:54 UTC, ClementWalter commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +fn test_exec_mstore_should_store_only_F_offset_1() {
`should_store_max_uint256_at_offset_1`

2023-09-07 11:54 UTC, ClementWalter commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +fn test_exec_mstore_should_store_1_offset_1() {
don't need this test

2023-09-07 11:54 UTC, ClementWalter commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +fn test_exec_mstore_should_store_0xFF_offset_1() {
don't need this test

2023-09-07 11:54 UTC, ClementWalter commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +fn test_exec_mstore_should_store_0xFF00_offset_1() {
don't need this test

2023-09-07 11:54 UTC, ClementWalter commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +fn test_exec_mstore_should_store_0xFF00_offset_0x20() {
don't need this test

2023-09-07 12:38 UTC, Quentash commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +fn test_exec_mstore_should_store_1_offset_1() {
Not really, this test was imported from https://github.com/ethereum/tests/blob/develop/src/GeneralStateTestsFiller/VMTests/vmIOandFlowOperations/mstoreFiller.yml ( as many others that I will now remove since they indeed don't really have plus-value )

2023-09-07 12:49 UTC, Quentash commented
Removed many unnecessary tests.
Reverted back to single pop.
Replaced "only_Fs" by "max_uint256".
Added to self to-do list to review english past participle.

2023-09-08 08:46 UTC, ClementWalter approved these changes

2023-09-08 08:52 UTC, merged