feat: add tests for JUMP instruction
kkrt-labs/kakarot-ssj pull request #291
Opened 2023-09-06 14:18 UTC by lambda-0x

## Pull Request type

Please check the type of change your PR introduces:

- [x] Other (please describe): adding test before implementing instruction as mentioned in issue

## What is the current behavior?

Resolves: #251

## What is the new behavior?

- evm.codes doesn't contain an example for this
- i couldn't find test for this in geth or kakarot cairo0 (lmk if i missed something)
- i think thats because there are only 2 cases, one in which location to which we need to jump is `JUMPDEST` (in that case its valid) else its invalid
- actually there is one more case in which: `0x5B` is part of data segment and is not an opcode (in an PUSHN) context.
  - kakarot 0 also doesn't handle this case, i will see geth's code and figure out how to implement this.

## Does this introduce a breaking change?

- [x] No

2023-09-06 15:27 UTC, lambda-0x commented
(test failure due unrelated to PR)

2023-09-06 15:36 UTC, Eikix commented
There is a third case but that can't be covered here for now, which is:
https://github.com/kkrt-labs/kakarot/issues/693

2023-09-06 15:38 UTC, lambda-0x commented
haha yes! just realized that.

2023-09-06 15:38 UTC, Eikix commented
Will start advertising it but the best source of truth we got is:
https://github.com/ethereum/execution-specs/

2023-09-06 16:22 UTC, lambda-0x commented
(added the third case as test, and marked it ignored for now)

2023-09-07 01:43 UTC, Eikix requested changes
after that lgtm

2023-09-07 01:43 UTC, Eikix commented on crates/evm/src/errors.cairo
> +const JUMP_OUT_OF_BOUND: felt252 = 'Kakarot: JumpOutOfBounds';
can you try a test case for jump out of bounds, first on evm.codes or check in the execution specs how it's handled
then in the test cases, to use this error msg

2023-09-07 10:54 UTC, lambda-0x commented on crates/evm/src/errors.cairo
> +const JUMP_OUT_OF_BOUND: felt252 = 'Kakarot: JumpOutOfBounds';
execution spec and geth gets this case handled for free because they just check if location to jump is in map of valid locations that is precomputed (thing that we discussed in telegram channel). good point will add a test for it.

2023-09-07 11:39 UTC, ClementWalter submitted a review, later dismissed
I'm fine with the logic of the tests, but prefer to have a named `counter` variable to clearly states that we push the input of the `JUMP` opcode

2023-09-07 11:39 UTC, ClementWalter commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +    ctx.stack.push(0x03);
```
let counter = 0x03
ctx.stash.push(counter)
```

to keep the evm.codes naming where JUMP takes `counter` from stack

2023-09-07 11:39 UTC, ClementWalter commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +    ctx.stack.push(0x02);
`let counter = 0x02` ...

2023-09-07 11:39 UTC, ClementWalter commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +    ctx.stack.push(0xFF);
`let counter = 0xFF` ...

2023-09-07 12:03 UTC, lambda-0x commented
(rebased to main, incase it fixes snapshot CI)

2023-09-07 16:13 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +    ctx.stack.push(0x03);
fyi this one is not resolved yet

2023-09-07 16:57 UTC, lambda-0x commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +    ctx.stack.push(0x03);
my bad, fixed

2023-09-07 17:07 UTC, enitrat commented on crates/evm/src/errors.cairo
> +const JUMP_OUT_OF_BOUND: felt252 = 'Kakarot: JumpOutOfBounds';
@eikix thoughts?

2023-09-08 08:09 UTC, enitrat commented on crates/evm/src/errors.cairo
> +const JUMP_OUT_OF_BOUND: felt252 = 'Kakarot: JumpOutOfBounds';
Let's remove it and only keep INVALID_JUMPDEST for both out of bounds jumps and non-jumpdest opcodes

2023-09-08 08:11 UTC, Eikix commented on crates/evm/src/errors.cairo
> +const JUMP_OUT_OF_BOUND: felt252 = 'Kakarot: JumpOutOfBounds';
I initially was fine with differentiating invalid dest and out of bounds
I checked EELS: https://github.com/ethereum/execution-specs/blob/fade6e95726c9c0b47b779fd8873b5737fbea3b3/src/ethereum/paris/vm/instructions/control_flow.py#L63

And realize we need to stick to spec

2023-09-08 08:15 UTC, enitrat commented on crates/evm/src/instructions/memory_operations.cairo
>          Result::Ok(())
I think you can remove the returned result here and it will still compile fine (maybe you'll need to remove the `;` after the panic line)

2023-09-08 08:15 UTC, enitrat commented on crates/evm/src/errors.cairo
> +const JUMP_INVALID_DESTINATION: felt252 = 'Kakarot: JumpInvalidDestination';
```suggestion
const INVALID_JUMP: felt252 = 'Kakarot: invalid JUMP';
```

maybe in the future we'll be able to have dynamic string error messages

2023-09-08 09:30 UTC, lambda-0x commented on crates/evm/src/errors.cairo
> +const JUMP_OUT_OF_BOUND: felt252 = 'Kakarot: JumpOutOfBounds';
got it

2023-09-08 09:51 UTC, lambda-0x commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +    assert(result.is_err(), 'invalid jump dest');
is just checks that its an error, doesn't assert the message. that is done below, also i think it would be redundant to use same error message as it would only be shown when test fails, in which case error variant should already contain that message.

2023-09-08 09:52 UTC, lambda-0x commented on crates/evm/src/instructions/memory_operations.cairo
>          Result::Ok(())
i followed the tasks list in the linked issue which says to add this panic

2023-09-08 09:53 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +    assert(result.is_err(), 'invalid jump dest');
ah sorry I got confused!

2023-09-08 09:54 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +    assert(result.is_err(), 'invalid jump dest');
then tbh this line can be removed as it's already covered by the line below

2023-09-08 10:26 UTC, lambda-0x commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +    assert(result.is_err(), 'invalid jump dest');
for consistency with other part of codebase i used this,

also ig doing it this way would make be easier to differentiate between either we failed test due to getting `Result::Ok(())` or a different error variant than expected.

2023-09-08 10:57 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> +    assert(result.is_err(), 'invalid jump dest');
ok let's keep it like this

2023-09-08 11:02 UTC, lambda-0x commented on crates/evm/src/errors.cairo
> +const JUMP_INVALID_DESTINATION: felt252 = 'Kakarot: JumpInvalidDestination';
this doesn't fit in felt252, should i change error contents to `KKT: error desc`?

2023-09-08 11:05 UTC, lambda-0x commented on crates/evm/src/instructions/memory_operations.cairo
>          Result::Ok(())
oh misunderstood what you mean

2023-09-08 11:10 UTC, enitrat commented on crates/evm/src/errors.cairo
> +const JUMP_INVALID_DESTINATION: felt252 = 'Kakarot: JumpInvalidDestination';
yes please, do it locally for this one I will do the rest for consistency https://github.com/kkrt-labs/kakarot-ssj/issues/326

2023-09-08 11:15 UTC, lambda-0x commented on crates/evm/src/errors.cairo
> +const JUMP_INVALID_DESTINATION: felt252 = 'Kakarot: JumpInvalidDestination';
cool

2023-09-08 14:52 UTC, enitrat submitted a review, later dismissed
lgtm!

2023-09-13 03:04 UTC, Eikix submitted a review, later dismissed

2023-09-13 03:05 UTC, Eikix commented
Approved, just rebase for conflicts

2023-09-13 04:44 UTC, Eikix approved these changes

2023-09-13 04:44 UTC, merged