feat: implement pop_type methods and use them
kkrt-labs/kakarot-ssj pull request #340
Opened 2023-09-11 14:48 UTC by lambda-0x

## Pull Request type

Please check the type of change your PR introduces:

- [x] Feature

## What is the current behavior?

Resolves: #337 

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [x] Yes

2023-09-12 14:24 UTC, ClementWalter commented on crates/evm/src/instructions/memory_operations.cairo
> +        let value: u8 = (popped.low & 0xFF).try_into().unwrap();
see the doc "value: 1-byte value to write in the [memory](https://www.evm.codes/about) (the least significant byte of the 32-byte stack value)."

2023-09-12 14:27 UTC, ClementWalter commented on crates/evm/src/stack.cairo
> +    fn pop_u32(ref self: Stack) -> Result<usize, EVMError>;
see https://book.cairo-lang.org/ch02-02-data-types.html?highlight=usize#integer-types

> Note that for now, the usize type is just an alias for u32; however, it might be useful when in the future Cairo can be compiled to MLIR

so depending on the usage, it's either `pop_u32() > u32` or `pop_usize() > usize` to avoid any future bug

2023-09-12 14:28 UTC, ClementWalter commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +    assert(ctx.stack.pop_eth_address().unwrap() == evm_address().into(), 'should be `evm_address`');
there will be other for sure, in CALLs for example

2023-09-12 14:29 UTC, ClementWalter commented on crates/evm/src/stack.cairo
> +    fn pop_u32(ref self: Stack) -> Result<usize, EVMError>;
actually the issue explicitly mentioned "Implement pop_usize" so plz do!

2023-09-12 14:29 UTC, ClementWalter requested changes
plz do as per the issue and rebase

2023-09-12 14:34 UTC, lambda-0x commented on crates/evm/src/instructions/memory_operations.cairo
> +        let value: u8 = (popped.low & 0xFF).try_into().unwrap();
okay geth seems to be truncating value as well.

2023-09-12 14:35 UTC, lambda-0x commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +    assert(ctx.stack.pop_eth_address().unwrap() == evm_address().into(), 'should be `evm_address`');
okay will recheck

2023-09-12 15:15 UTC, lambda-0x commented on crates/evm/src/tests/test_instructions/test_environment_information.cairo
> +    assert(ctx.stack.pop_eth_address().unwrap() == evm_address().into(), 'should be `evm_address`');
i rechecked all uses of `pop` and `pop_n`, i don't see any.

> there will be other for sure, in CALLs for example

system operations like `call`, `staticcall` are not yet implemented.

2023-09-12 15:21 UTC, lambda-0x commented
snapshot test failing because one of the test now uses the new method `pop_eth_address` instead of just calling `pop` (as it doesn't need to convert to `EthAddress` and back)

2023-09-12 15:24 UTC, lambda-0x commented
apart from that test perf has increased, ignoring that test:

```
$ python scripts/compare_snapshot.py
Archive:  gas_snapshot.zip
  inflating: gas_snapshot.json       
****IMPROVEMENTS****
evm::tests::test_instructions::test_environment_information::test_calldatacopy_basic 1744440 --> 1674700 -4.00 %
evm::tests::test_instructions::test_environment_information::test_calldatacopy_type_conversion_error 620230 --> 558590 -9.94 %
evm::tests::test_instructions::test_environment_information::test_calldatacopy_with_offset 1592580 --> 1522840 -4.38 %
evm::tests::test_instructions::test_environment_information::test_calldatacopy_with_out_of_bound_bytes 2260160 --> 2190420 -3.09 %
evm::tests::test_instructions::test_environment_information::test_calldatacopy_with_out_of_bound_bytes_multiple_words 4816810 --> 4747070 -1.45 %
evm::tests::test_instructions::test_environment_information::test_codecopy_basic 2142266 --> 2072526 -3.26 %
evm::tests::test_instructions::test_environment_information::test_codecopy_type_conversion_error 620300 --> 558660 -9.94 %
evm::tests::test_instructions::test_environment_information::test_codecopy_with_offset 2029466 --> 1959726 -3.44 %
evm::tests::test_instructions::test_environment_information::test_codecopy_with_out_of_bound_bytes 2363536 --> 2293796 -2.95 %
evm::tests::test_instructions::test_environment_information::test_codecopy_with_out_of_bound_offset 1993436 --> 1923696 -3.50 %
evm::tests::test_instructions::test_environment_information::test_returndata_copy_basic 4148102 --> 4078362 -1.68 %
evm::tests::test_instructions::test_environment_information::test_returndata_copy_overflowing_add_error 575380 --> 505640 -12.12 %
evm::tests::test_instructions::test_environment_information::test_returndata_copy_type_conversion_error 415570 --> 353930 -14.83 %
evm::tests::test_instructions::test_environment_information::test_returndata_copy_with_multiple_words 4004552 --> 3934812 -1.74 %
evm::tests::test_instructions::test_environment_information::test_returndata_copy_with_offset 4052402 --> 3982662 -1.72 %
evm::tests::test_instructions::test_environment_information::test_returndata_copy_with_out_of_bound_bytes 575380 --> 505640 -12.12 %
evm::tests::test_instructions::test_memory_operations::test_exec_mstore8_should_store_last_uint8_offset_31 631124 --> 572864 -9.23 %
evm::tests::test_instructions::test_memory_operations::test_exec_mstore8_should_store_last_uint8_offset_63 631124 --> 572864 -9.23 %
evm::tests::test_instructions::test_memory_operations::test_exec_mstore8_should_store_uint8_offset_30 631124 --> 572864 -9.23 %
evm::tests::test_instructions::test_memory_operations::test_exec_mstore8_should_store_uint8_offset_31 631124 --> 572864 -9.23 %
evm::tests::test_instructions::test_memory_operations::test_exec_mstore8_should_store_uint8_offset_31_then_uint8_offset_30 1018238 --> 901718 -11.44 %


****WORSENED****
Overall gas change: performance improvement, gas consumption-0.57 %
```

2023-09-12 16:22 UTC, enitrat commented
> apart from that test perf has increased, ignoring that test:
> 
> ```
> $ python scripts/compare_snapshot.py
> Archive:  gas_snapshot.zip
>   inflating: gas_snapshot.json       
> ****IMPROVEMENTS****
> evm::tests::test_instructions::test_environment_information::test_calldatacopy_basic 1744440 --> 1674700 -4.00 %
> evm::tests::test_instructions::test_environment_information::test_calldatacopy_type_conversion_error 620230 --> 558590 -9.94 %
> evm::tests::test_instructions::test_environment_information::test_calldatacopy_with_offset 1592580 --> 1522840 -4.38 %
> evm::tests::test_instructions::test_environment_information::test_calldatacopy_with_out_of_bound_bytes 2260160 --> 2190420 -3.09 %
> evm::tests::test_instructions::test_environment_information::test_calldatacopy_with_out_of_bound_bytes_multiple_words 4816810 --> 4747070 -1.45 %
> evm::tests::test_instructions::test_environment_information::test_codecopy_basic 2142266 --> 2072526 -3.26 %
> evm::tests::test_instructions::test_environment_information::test_codecopy_type_conversion_error 620300 --> 558660 -9.94 %
> evm::tests::test_instructions::test_environment_information::test_codecopy_with_offset 2029466 --> 1959726 -3.44 %
> evm::tests::test_instructions::test_environment_information::test_codecopy_with_out_of_bound_bytes 2363536 --> 2293796 -2.95 %
> evm::tests::test_instructions::test_environment_information::test_codecopy_with_out_of_bound_offset 1993436 --> 1923696 -3.50 %
> evm::tests::test_instructions::test_environment_information::test_returndata_copy_basic 4148102 --> 4078362 -1.68 %
> evm::tests::test_instructions::test_environment_information::test_returndata_copy_overflowing_add_error 575380 --> 505640 -12.12 %
> evm::tests::test_instructions::test_environment_information::test_returndata_copy_type_conversion_error 415570 --> 353930 -14.83 %
> evm::tests::test_instructions::test_environment_information::test_returndata_copy_with_multiple_words 4004552 --> 3934812 -1.74 %
> evm::tests::test_instructions::test_environment_information::test_returndata_copy_with_offset 4052402 --> 3982662 -1.72 %
> evm::tests::test_instructions::test_environment_information::test_returndata_copy_with_out_of_bound_bytes 575380 --> 505640 -12.12 %
> evm::tests::test_instructions::test_memory_operations::test_exec_mstore8_should_store_last_uint8_offset_31 631124 --> 572864 -9.23 %
> evm::tests::test_instructions::test_memory_operations::test_exec_mstore8_should_store_last_uint8_offset_63 631124 --> 572864 -9.23 %
> evm::tests::test_instructions::test_memory_operations::test_exec_mstore8_should_store_uint8_offset_30 631124 --> 572864 -9.23 %
> evm::tests::test_instructions::test_memory_operations::test_exec_mstore8_should_store_uint8_offset_31 631124 --> 572864 -9.23 %
> evm::tests::test_instructions::test_memory_operations::test_exec_mstore8_should_store_uint8_offset_31_then_uint8_offset_30 1018238 --> 901718 -11.44 %
> 
> 
> ****WORSENED****
> Overall gas change: performance improvement, gas consumption-0.57 %
> ```
> 

Likely due to replacing pop_n by n pops. We might get completely rid of pop_n for pops known at compile time

2023-09-12 16:27 UTC, enitrat commented on crates/evm/src/stack.cairo
> +    fn pop_u32(ref self: Stack) -> Result<usize, EVMError>;
Comment from Lucas:

Usize is very different, if we switch to a smaller field the usize max value would be impacted. For timestamp we don’t want it to change

2023-09-13 04:28 UTC, Eikix commented on crates/evm/src/stack.cairo
> +        let item: u32 = Into::<u256, Result<u32, EVMError>>::into(item)?;
should we have a pop_u32?

2023-09-13 04:28 UTC, lambda-0x commented on crates/evm/src/stack.cairo
> +        let item: u32 = Into::<u256, Result<u32, EVMError>>::into(item)?;
see: https://github.com/kkrt-labs/kakarot-ssj/pull/340#discussion_r1323132340

2023-09-13 04:29 UTC, lambda-0x commented on crates/evm/src/stack.cairo
> +        let item: u32 = Into::<u256, Result<u32, EVMError>>::into(item)?;
usize is alias for u32, will update the type in the method so remove confusion

2023-09-13 07:27 UTC, Eikix reviewed
one question

2023-09-13 07:27 UTC, Eikix commented on crates/evm/src/stack.cairo
> +        let item: usize = Into::<u256, Result<usize, EVMError>>::into(item)?;
i don't understand this latest commit,
we have a pop_usize until thanks to this pr,

are you suggesting to replace all pop_usize with pop_u32?
 
and then to replace accordingly?

2023-09-13 08:19 UTC, lambda-0x commented on crates/evm/src/stack.cairo
> +        let item: usize = Into::<u256, Result<usize, EVMError>>::into(item)?;
i was suggesting doing that but we decide to keep it `usize` https://github.com/kkrt-labs/kakarot-ssj/pull/340#discussion_r1323293298

2023-09-13 08:20 UTC, lambda-0x commented on crates/evm/src/stack.cairo
> +        let item: usize = Into::<u256, Result<usize, EVMError>>::into(item)?;
that last commit was just to resolve confusion because i was using `u32` in a function that returns `usize`. `usize` is alias of `u32` so doesn't really matter

2023-09-13 11:48 UTC, lambda-0x commented on crates/evm/src/stack.cairo
> +        let item: usize = Into::<u256, Result<usize, EVMError>>::into(item)?;
i am using `pop_usize` everywhere, did i miss it somewhere?

2023-09-13 12:09 UTC, enitrat commented on crates/evm/src/instructions/memory_operations.cairo
> +        let popped = self.stack.pop()?;
wrong variable name

2023-09-13 12:23 UTC, lambda-0x commented on crates/evm/src/instructions/memory_operations.cairo
> +        let popped = self.stack.pop()?;
no thats intentional because 1st popped value is `offset` and second popped value is `value`

2023-09-13 12:26 UTC, lambda-0x commented on crates/evm/src/instructions/memory_operations.cairo
> +        let popped = self.stack.pop()?;
or do you mean using the value directly without intermediate `popped` variable?

i think this is much harder to read, so i created an intermediate value
```rust
let value = (self.stack.pop()?.low & 0xFF).try_into().unwrap();
```

2023-09-13 13:04 UTC, enitrat commented on crates/evm/src/instructions/memory_operations.cairo
> +        let popped = self.stack.pop()?;
>  1st popped value is offset and second popped value is value

yes, but you named the second popped value `popped`?

2023-09-13 13:08 UTC, enitrat commented on crates/evm/src/instructions/memory_operations.cairo
> +        let popped = self.stack.pop()?;
`popped` is too much connotated to an array of popped values, here we can give it more meaning

2023-09-13 13:23 UTC, lambda-0x commented on crates/evm/src/instructions/memory_operations.cairo
> +        let popped = self.stack.pop()?;
i don't think `stack_top` would be a good idea as well because that was the `offset` value we removed from stack just above. should i just name it `value` so it will be shadowed by the line below.

2023-09-13 15:24 UTC, enitrat commented on crates/evm/src/instructions/memory_operations.cairo
> +        let popped = self.stack.pop()?;
fine for me

2023-09-13 15:44 UTC, Eikix commented on crates/evm/src/stack.cairo
> +        let item: usize = Into::<u256, Result<usize, EVMError>>::into(item)?;
line 87 no?

2023-09-13 15:46 UTC, enitrat submitted a review, later dismissed
LGTM

2023-09-13 16:56 UTC, lambda-0x commented on crates/evm/src/stack.cairo
> +        let item: usize = Into::<u256, Result<usize, EVMError>>::into(item)?;
ser thats the implementation of `pop_usize` :smile:

2023-09-13 17:02 UTC, lambda-0x commented
will rebase and use this new methods for PR (https://github.com/kkrt-labs/kakarot-ssj/pull/328) as well

2023-09-14 02:57 UTC, Eikix commented on crates/evm/src/stack.cairo
> +        let item: usize = Into::<u256, Result<usize, EVMError>>::into(item)?;
wtf im drunk thanks ser

2023-09-14 02:58 UTC, Eikix approved these changes
lgtm 🙏

2023-09-14 02:58 UTC, merged

2023-09-14 04:19 UTC, lambda-0x commented on crates/evm/src/stack.cairo
> +        let item: usize = Into::<u256, Result<usize, EVMError>>::into(item)?;
:laughing: