feat: feat/implement_0x90_SWAP1_Opcode
kkrt-labs/kakarot-ssj pull request #342
Opened 2023-09-11 17:34 UTC by Noeljarillo

Implementation of Swap_i and swap_n Opcodes

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

2023-09-11 17:35 UTC, Noeljarillo commented
Now hope is all good! still need to add more edge case tests like old cairo implementation, but wanted to check all is good before, Ive followed PUSH implementation

2023-09-12 04:21 UTC, danilowhk commented on crates/evm/src/instructions/exchange_operations.cairo
> +    fn exec_swap_i(ref context: ExecutionContext, i: u8) -> Result<(), EVMError> {
I think since there is already 

``context.stack.swap_i(i)`` this function becomes redundant.

2023-09-12 04:21 UTC, danilowhk commented on crates/evm/src/instructions/exchange_operations.cairo
> +        internal::exec_swap_i(ref self, 1);
use context.stack.swap_i(i) directly

2023-09-12 04:21 UTC, danilowhk commented on crates/evm/src/instructions/exchange_operations.cairo
> +        internal::exec_swap_i(ref self, 2);
Same for all other swaps

2023-09-12 08:48 UTC, Eikix commented on crates/evm/src/instructions/exchange_operations.cairo
> +    fn exec_swap1(ref self: ExecutionContext) {
Careful, your opcodes are not returning the required signature,
They need to return a `Result<(), EVMError>`.

2023-09-12 08:50 UTC, Eikix commented on crates/evm/src/instructions/exchange_operations.cairo
> +        internal::exec_swap_i(ref self, 1);
```suggestion
        context.stack.swap_i(i.into())
```

2023-09-12 08:50 UTC, Eikix commented on crates/evm/src/interpreter.cairo
> +            context.exec_swap1();
```suggestion
            return context.exec_swap1();
```

2023-09-12 08:50 UTC, Eikix commented on crates/evm/src/interpreter.cairo
> +            context.exec_swap2();
same for all other swaps

2023-09-12 08:51 UTC, Eikix commented on crates/evm/src/tests/test_instructions/test_exchange_operations.cairo
> +    assert(ctx.stack.peek().unwrap() == 2, 'Top should be now [1]');
```suggestion
    assert(ctx.stack.peek().unwrap() == 2, 'Top should be now 2');
```

2023-09-12 08:54 UTC, Eikix commented on crates/evm/src/tests/test_instructions/test_exchange_operations.cairo
> +    ctx.stack.push(2).unwrap();
it's not so clear using these numbers, I'd advise using:
0x01 for the top of the stack element
0xff for the swapped element
0x00 for the elements in between

2023-09-12 08:55 UTC, Eikix commented on crates/evm/src/tests/test_instructions/test_exchange_operations.cairo
> +    ctx.stack.push(2).unwrap();
1
0
0
0
0
0
0xff

-> exec_swap6

->
0xff
0
0
0
0
0
1

2023-09-12 08:56 UTC, Eikix requested changes
Nice PR!

2023-09-12 10:40 UTC, enitrat reviewed
Your swap operations need to return Result<(), EVMError>

They will actually just return whatever `self.stack.swap_i(<value>)` returns

2023-09-12 10:40 UTC, enitrat commented on crates/evm/src/instructions/exchange_operations.cairo
> +    fn exec_swap_i(ref context: ExecutionContext, i: u8) -> Result<(), EVMError> {
Yes, you can remove it

2023-09-12 10:40 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_exchange_operations.cairo
> +fn test_swap1() {
```suggestion
fn test_exec_swap1() {
```

Same for all other test names

2023-09-12 17:27 UTC, Noeljarillo commented on crates/evm/src/tests/test_instructions/test_exchange_operations.cairo
> +    assert(ctx.stack.peek().unwrap() == 2, 'Top should be now[2]');
makes sense will do number!

2023-09-12 17:28 UTC, Noeljarillo commented on crates/evm/src/tests/test_instructions/test_exchange_operations.cairo
> +    ctx.stack.push(2).unwrap();
makes sense!

2023-09-12 18:17 UTC, Noeljarillo commented on crates/evm/src/instructions/exchange_operations.cairo
> +    fn exec_swap_i(ref context: ExecutionContext, i: u8) -> Result<(), EVMError> {
https://github.com/Noeljarillo/kakarot-ssj/blob/feat/implement_0x90_-_SWAP1_Opcode/crates/evm/src/instructions/push_operations.cairo followed the implementation of push

2023-09-12 20:04 UTC, Noeljarillo commented
Fixed Returns on function and op code call, aslo added suggested changes to tests.

I've tried delete swap_i() function but after lot of thinkering could not delete as calling context.stack.swap_i() from every swap_n gave me errors that could not find the function. But prototyped functions and PUSH implementation is by using swap_i()

2023-09-13 15:54 UTC, enitrat reviewed
> calling context.stack.swap_i() from every swap_n gave me errors that could not find the function

You have to call `self.stack.swap_i`, as the swap_i are methods of the ExecutionContext type, which is passed as a  `self` parameter

2023-09-13 15:54 UTC, enitrat commented on crates/evm/src/instructions/exchange_operations.cairo
> +    fn exec_swap_i(ref context: ExecutionContext, i: u8) -> Result<(), EVMError> {
For push it's different because we have an extra line to read data at `i`. Here it's not useful at all

2023-09-13 16:05 UTC, Noeljarillo commented
Understood, I'll implement the way you suggest!

2023-09-13 18:42 UTC, Noeljarillo commented
Million thanks @enitrat I was referencing wrong the call to swap i by calling it from context.stack instead of self, now it works as intended!

2023-09-14 03:33 UTC, enitrat commented on crates/evm/src/tests/test_instructions/test_exchange_operations.cairo
> +    assert(ctx.stack.peek().unwrap() == 0xf, 'Top should be now 0xf');
you also need to check that value at index `i` (here, one) has been swapped correctly. you can use `peek_at` for that

2023-09-14 16:19 UTC, enitrat approved these changes
lgtm!

2023-09-14 22:47 UTC, Eikix approved these changes
lgtm 🥕

2023-09-14 22:47 UTC, merged

2023-09-17 17:30 UTC, enitrat commented
Closes #302
Closes #303
Closes #304
Closes #305
Closes #306
Closes #307 
Closes #308 
Closes #309 
Closes #310 
Closes #311 
Closes #312
Closes #313 
Closes #313 
Closes #314 
Closes #315  
Closes #316 
Closes #317