ci: log result
kkrt-labs/kakarot-ssj pull request #347
Opened 2023-09-14 03:56 UTC by enitrat

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [x] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Resolves: #

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

2023-09-14 10:06 UTC, ClementWalter commented on .github/workflows/gas_reports.yml
>            echo "::set-output name=result::${result}"
can remove this line I think (for setting the setp.output value, not used anymore, and generating a deprecation warning in the CI)

2023-09-14 10:08 UTC, ClementWalter requested changes
can we make the small modif required in the meantime to clear these warnings

[compare-snapshot](https://github.com/kkrt-labs/kakarot-ssj/actions/runs/6180880394/job/16778019564)
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/setup-python@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

[compare-snapshot](https://github.com/kkrt-labs/kakarot-ssj/actions/runs/6180880394/job/16778019564#step:5:15)
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

2023-09-14 11:18 UTC, enitrat commented on .github/workflows/gas_reports.yml
>            echo "::set-output name=result::${result}"
ah yes indeed. I though we still had the comment active for local branches. will change

2023-09-18 06:56 UTC, ClementWalter approved these changes

2023-09-18 06:56 UTC, ClementWalter commented on .github/workflows/gas_reports.yml
> +        uses: actions/setup-python@v3
can't we use `v4` as in the `gas_snapshot` workflow?

2023-09-18 11:03 UTC, enitrat commented on .github/workflows/gas_reports.yml
> +        uses: actions/setup-python@v3
I updated it to v4

2023-09-25 03:20 UTC, enitrat commented
@ClementWalter can we merge?

2023-09-25 05:08 UTC, ClementWalter approved these changes

2023-09-25 05:09 UTC, merged