feat: missing stack features & refactoring
kkrt-labs/kakarot-ssj pull request #35
Opened 2023-05-11 13:57 UTC by enitrat

Refactors the Stack implementation and adds missing methods like `pop_n` and `swap_i`
This implementation is a bit closer to Cairo0's implementation, but with more abstractions thanks to Cairo1's features.

One thing I would like to discuss is: should we panic (like when trying to `pop_n` with `n>len`) or return Options that will be handled afterwards?

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-05-24 11:08 UTC, ClementWalter requested changes

2023-05-24 11:08 UTC, ClementWalter commented on tests/test_stack.cairo
> +    let high = stack.items.get(0);
we shouldn't access this internal impl detail given the name of the test, only assert that `stack.peek()` returns the pushed value

2023-05-24 11:08 UTC, ClementWalter commented on tests/test_stack.cairo
> +    stack.len = constants::STACK_MAX_DEPTH;
see comment above, I don't think this is a good test. Can we `loop` to fill the stack instead?

2023-05-24 11:08 UTC, ClementWalter commented on tests/test_stack.cairo
> +fn test__pop__should_pop_an_element_to_the_stack() {
pop *from* the stack

2023-05-24 11:08 UTC, ClementWalter commented on tests/test_stack.cairo
> +    assert(*elements[2] == 1, 'wrong result');
is it required to add an error message in the `assert` ? this "wrong result" is not very informative

2023-05-24 11:08 UTC, ClementWalter commented on src/stack.cairo
>      fn peek(ref self: Stack) -> Option<u256>;
why does peek return an Option btw?

2023-05-24 16:39 UTC, enitrat commented on tests/test_stack.cairo
> +    assert(stack.len() == 0, 'stack length should be 0');
I'm in favor of keeping both actually. In the future, we might want to have len as a private field (which we can't do yet)

2023-05-24 16:43 UTC, enitrat commented on src/stack.cairo
> +        if index > self.len() {
Good catch

2023-05-24 16:44 UTC, enitrat commented on src/stack.cairo
> +        let real_index: felt252 = index.into() * 2;
It acted like a `push_u256` instead of a more generic `insert_u256` at any position. We have tests but only on the Stack itself, and since they don't cover insertion at random places because that doesn't happen in a stack.

2023-05-24 16:46 UTC, enitrat commented on tests/test_stack.cairo
> +fn test__push__should_add_an_element_to_the_stack() {
What for? They're already inside the `test_stack` module

2023-05-24 16:48 UTC, enitrat commented on tests/test_stack.cairo
> +    stack.len = constants::STACK_MAX_DEPTH;
Why not? We know that `stack.push` increments the length, and that when the length is maximal, we can't push anymore.

2023-05-24 17:46 UTC, ClementWalter commented on tests/test_stack.cairo
> +    assert(stack.len() == 0, 'stack length should be 0');
ok so maybe just make sure that we don't use any `.len` outside of the `impl`

2023-05-24 17:49 UTC, ClementWalter commented on tests/test_stack.cairo
> +fn test__push__should_add_an_element_to_the_stack() {
namespace for each system under testing (push, peek, pop, etc.) like you could have in js

```
describe("Stack", () => {
    describe("push", () => {
        it("should add an item", () => {}
    }
}
```

2023-05-24 18:49 UTC, enitrat commented on tests/test_stack.cairo
> +fn test__push__should_add_an_element_to_the_stack() {
The best I can do is split them in different modules

2023-05-25 09:39 UTC, ClementWalter commented on tests/test_stack.cairo
> +fn test__push__should_add_an_element_to_the_stack() {
like this?

```
mod push {
    fn test_should_add_an_element()
}
```

sounds good to me, and shorten the function names then

2023-05-25 09:45 UTC, ClementWalter commented on tests/test_stack.cairo
> +    assert(*elements[2] == 1, 'wrong result');
is it something that could change in the future?

2023-06-02 19:13 UTC, enitrat commented on tests/test_stack.cairo
> +    assert(stack.len() == 0, 'stack length should be 0');
yep 👍

2023-06-02 19:22 UTC, enitrat commented on src/stack.cairo
>      fn peek(ref self: Stack) -> Option<u256>;
Makes sense. My reasoning was that in the specific case of KKT, we shouldn't encounter a case where we would pop an empty stack; and if such a case were to happen, we would want to panic. That's how it was done in the v0 implementation. 
On the other hand, given that peek is just a `view` operation, I thought that there might be use cases where returning `None` could be useful.
I will add your changes if you think it is the right way

2023-06-05 10:44 UTC, ClementWalter commented on src/stack.cairo
>      fn peek(ref self: Stack) -> Option<u256>;
ok so looking at the cairo 0 codebase, the only place where we actually use this `peek` method is for DUP ops, which have an error case that "Not enough values on the stack." (see https://www.evm.codes/#81?fork=shanghai) that we'll want to handle (we just panic in cairo 0). So let's keep the `Option`

2023-06-05 11:53 UTC, enitrat commented on src/stack.cairo
>      fn peek(ref self: Stack) -> Option<u256>;
I will also modify `pop` to return an Option as well for consistency purposes.

2023-06-14 16:47 UTC, enitrat commented
@ClementWalter everything should be good now

2023-06-16 10:22 UTC, ClementWalter commented on src/stack.cairo
>      fn peek(ref self: Stack) -> Option<u256>;
so pop & peek return `Option` but `pop_n` and `peek_at` no, we should probably have option everywhere then right?

2023-06-16 10:23 UTC, ClementWalter commented on src/stack.cairo
> +        if self.len == constants::STACK_MAX_DEPTH {
can we use `self.len()` everywhere?

2023-06-16 10:24 UTC, ClementWalter commented on src/stack.cairo
> +        if self.len == constants::STACK_MAX_DEPTH {
or maybe `self.len`, but mixing is confusing

2023-06-16 10:26 UTC, ClementWalter commented on src/stack.cairo
> +        let index_from_top = position_0 - index;
it's actually `index_from_top` in argument and `index = position_0 - index_from_top` here right?

2023-06-16 10:26 UTC, ClementWalter commented on src/stack.cairo
> +    #[inline(always)]
inlining saves steps right?

2023-06-16 10:30 UTC, ClementWalter reviewed
the stack overflow is much better with the loop!

2023-06-16 11:01 UTC, enitrat commented on src/stack.cairo
> +        if self.len == constants::STACK_MAX_DEPTH {
I used `self.len()` for all "views" of the length of the array and `self.len` when there's a mutation of the length.

2023-06-16 11:07 UTC, enitrat commented on src/stack.cairo
> +        let index_from_top = position_0 - index;
For consistency with other methods, `index` always refers to the item from the top of the Stack. The variable naming here `index_from_top` is indeed not ideal, I think `position_item` makes more sense

2023-06-16 11:08 UTC, enitrat commented on src/stack.cairo
> +    #[inline(always)]
yes, it avoids a function call

2023-06-16 11:11 UTC, enitrat commented on src/stack.cairo
>      fn peek(ref self: Stack) -> Option<u256>;
I think it depends on how we want to manage eventual errors if there are any. I don't know enough about the context in which these methods are called, but adding Option adds small overhead costs. If KKT is built in a way where we're sure that `pop_n` and `peek_at` should always panic in case of over/underflow, then I think we should keep it this way.

2023-06-29 15:13 UTC, enitrat commented
ping @ClementWalter, can we get this one merged and come back on it later if required?

2023-07-26 11:19 UTC, ClementWalter approved these changes

2023-07-26 11:20 UTC, merged