[WIP] docs: evm-machine design doc
kkrt-labs/kakarot-ssj pull request #351
Opened 2023-09-14 18:13 UTC by enitrat

## Pull Request type

In this design document, we dive into a refactor of the Kakarot's EVM-Machine implementation, compatible with Cairo's limitations raised in https://github.com/starkware-libs/cairo/issues/4032. 
The accepted proposed design will need to: 
- Be easily refactorable
- Have a low overhead cost compared to the one originally planned
- Not introduce development complexity in other parts of the code

I believe that the proposed one performs well in all the points mentioned above. Please discuss it extensively!

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Resolves: #

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

2023-09-14 22:21 UTC, Eikix reviewed
What are the limitations of this approach?

2023-09-15 03:59 UTC, enitrat commented
> What are the limitations of this approach?

It's a bit more expensive as we need to track each stack/memory's context-related segment length in a dict instead of as a simple variable.
Also, this imposes a limit on the maximum amount of memory space a context can allocate.

2023-09-15 04:38 UTC, Eikix commented
> > What are the limitations of this approach?
> 
> 
> 
> It's a bit more expensive as we need to track each stack/memory's context-related segment length in a dict instead of as a simple variable.
> 
> Also, this imposes a limit on the maximum amount of memory space a context can allocate.

Let's discuss it in our weekly
What is the limit on memory space per context?

2023-09-15 04:44 UTC, enitrat commented
> the gas costs required to have a memory containing
> 125000 words is above the 30M gas limit. We will use this heuristic to bound the
> maximum size of the memory to 125000 256-bits words. Therefore, we will bound
> the maximum size of the memory to 125000 256-bits words.

2023-09-19 04:39 UTC, enitrat commented
@Eikix If you're okay with it I propose to merge the current design proposal, and to apply any modifications from SW's feedback in a new PR

2023-09-19 05:02 UTC, Eikix commented on docs/general/model/execution_context.md
> +    +memory: Memory
it seems this data structure does not match the data structure below:
- machine
- executioncontext 
etc.

2023-09-19 05:03 UTC, enitrat commented on docs/general/model/execution_context.md
> +    +memory: Memory
Ah, yes, indeed, thanks for pointing this out, I need to rework this section as well

2023-09-21 03:57 UTC, enitrat commented
@Eikix Reworked this:
- Changes brought to the ExecutionContext docs
- The Storage section has been entirely reworked

2023-09-21 04:12 UTC, Eikix commented on docs/general/machine.md
> +- Each execution context has a `parent_context` field, which is the numerical
is this true? the classDiagram says Nullable<ExecutionContext>

2023-09-21 04:12 UTC, Eikix commented on docs/general/machine.md
> +- Each execution context has a `child_context` field, which is the numerical
same q

2023-09-21 04:26 UTC, Eikix commented on docs/general/machine.md
> +      local_changes: Felt252Dict<felt252>,
what if the local changes are u256?

2023-09-21 04:27 UTC, Eikix commented on docs/general/machine.md
> +      local_changes: Felt252Dict<felt252>,
https://github.com/Eikix/kakarot/blob/aec81a483c3862bd71e0d55850a64f338434b4bc/src/kakarot/accounts/contract/library.cairo#L25

2023-09-21 04:31 UTC, Eikix commented on docs/general/machine.md
> +        local_changes: Felt252Dict~felt252~,
should journal expand its logic to `created_contracts` and `destroyed_contracts`?
as well as contract account nonce (if the contract account runs many create tx, nonce should be optimistically increased, until tx is finalized, and we finally write the final nonce to storage)

2023-09-21 04:31 UTC, Eikix commented on docs/general/machine.md
> +        reverted: bool,
should reverted / stopped be a status enum?

2023-09-21 04:50 UTC, enitrat commented on docs/general/machine.md
> +      local_changes: Felt252Dict<felt252>,
Yes they're actually always u256 indeed

2023-09-21 07:04 UTC, enitrat commented on docs/general/machine.md
> +        reverted: bool,
like
```rust
enum Status{
Active,
Stopped,
Reverted
}
```
?

2023-09-21 07:05 UTC, Eikix commented on docs/general/machine.md
> +        reverted: bool,
Yeah

2023-09-22 10:17 UTC, enitrat commented
@Eikix Changes applied

2023-09-22 10:58 UTC, Eikix approved these changes
lgtm 🔥

2023-09-22 11:10 UTC, Eikix requested changes
mb just noticed this PR does not have mentions of "dirtyStorage"? 
is dirtyStorage the equivalent of `local_changes`?
should we modify the other pr #360

2023-09-22 11:16 UTC, enitrat commented
>mb just noticed this PR does not have mentions of "dirtyStorage"?
>is dirtyStorage the equivalent of local_changes?
>should we modify the other pr https://github.com/kkrt-labs/kakarot-ssj/pull/360

dirtyStorage is a name that is unique to Geth. For us, it's the combination of `local_changes` and `global_changes`.

2023-09-22 11:17 UTC, Eikix approved these changes

2023-09-22 11:17 UTC, merged