feat: implement eth transaction validate
kkrt-labs/kakarot-ssj pull request #536
Opened 2023-11-11 13:11 UTC by bajpai244

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Transaction validation is not implemented.

Resolves: #523 

## What is the new behavior?

- The logic was transaction validation has been implemented.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2023-11-13 09:00 UTC, Eikix commented on crates/utils/src/eth_transaction.cairo
> +struct ValidateTxParam {
I'm not sure this name conveys semantic meaning,
It either feels like the name of this struct is just  "valide_eth_tx input param" which is weird,
or that there's a class of transaction called a Validate Tx, and this is its params,
like `DeclareTxParam`

2023-11-13 09:01 UTC, Eikix commented on crates/utils/src/eth_transaction.cairo
> +    tx_data: Span<u8>,
```suggestion
    encoded_tx: Span<u8>,
```

This would help differentiate with calldata

2023-11-13 09:04 UTC, Eikix commented on crates/utils/src/eth_transaction.cairo
> +struct ValidateTxParam {
How about 
`TransactionMetadata` that would contain sender_address, account_nonce, chain_id, signature

And encoded_tx_data would be separated, as it's not considered metadata, and validate_eth_tx would take two arguments and not one

2023-11-13 09:05 UTC, Eikix commented on crates/utils/src/eth_transaction.cairo
> +            return Result::Err(EthTransactionError::AccountNonceIsIncorrect);
I suggest SomethingIsSomeway -> SomewaySomething
IncorrectAccountNonce

IncorrectChainId

2023-11-13 09:06 UTC, Eikix commented on crates/utils/src/eth_transaction.cairo
> +
can we add a TODO, we need to also check maxfee = gas_price * gas_limit 

because : user signs on gas_price and gas_limit, but we inject maxfee in the starknet tx for them in the rpc, and there is no way for them to check we dont put an infinite maxfee

2023-11-13 09:07 UTC, Eikix commented on crates/utils/src/eth_transaction.cairo
> +
this can be a standalone issue for when we check in RPC that we respect this invariant

2023-11-13 09:08 UTC, Eikix requested changes
great encapsulation, it's way easier for us to test this feature;D 
nice thinking and good design, a few proposed changes for semantics and but overall lgtm

2023-11-13 14:03 UTC, bajpai244 commented on crates/utils/src/eth_transaction.cairo
> +struct ValidateTxParam {
I agree with this refactor, implemented via [this](https://github.com/kkrt-labs/kakarot-ssj/pull/536/commits/2dc1c00afe12b224beaa2ec1dad2f476afa11f20) commit.

2023-11-13 14:20 UTC, bajpai244 commented on crates/utils/src/eth_transaction.cairo
> +    tx_data: Span<u8>,
makes sense, done via [this](https://github.com/kkrt-labs/kakarot-ssj/pull/536/commits/41fbc2644a31798522450e49ae19a6789771ba2d) commit.

2023-11-14 05:24 UTC, bajpai244 commented on crates/utils/src/eth_transaction.cairo
> +
I am adding a TODO for this now, but if we know the gas_price and gas_limit, why does the RPC need to be provide this then?

We can simply calculate this on the smart contracts itself. Lemme know what u think.

2023-11-14 05:30 UTC, bajpai244 commented on crates/utils/src/eth_transaction.cairo
> +            return Result::Err(EthTransactionError::AccountNonceIsIncorrect);
These names sound better, completed via [this](https://github.com/kkrt-labs/kakarot-ssj/pull/536/commits/f889e5119b2880a97ad744d5807e89c84dd90308) commit.

2023-11-14 05:30 UTC, bajpai244 commented on crates/utils/src/eth_transaction.cairo
> +
I have added a TODO as of now via [this](https://github.com/kkrt-labs/kakarot-ssj/pull/536/commits/e0352e3908a474c15625824587368c040701bb9c) commit.

2023-11-14 08:41 UTC, Eikix commented on crates/utils/src/eth_transaction.cairo
> +
> I am adding a TODO for this now, but if we know the gas_price and gas_limit, why does the RPC need to be provide this then?
> 
> We can simply calculate this on the smart contracts itself. Lemme know what u think.

You need to provide maxFee parameter of the Starknet transaction at the RPC level, this is a protocol parameter

2023-11-14 08:41 UTC, Eikix approved these changes
lgtm

2023-11-14 08:42 UTC, Eikix commented on crates/utils/src/eth_transaction.cairo
> +            return Result::Err(EthTransactionError::IncoorectChainId);
typo

2023-11-14 08:43 UTC, Eikix commented on crates/utils/src/eth_transaction.cairo
> +        param: TransactionMetadata, encoded_tx_data: Span<u8>
```suggestion
        tx_metadata: TransactionMetadata, encoded_tx_data: Span<u8>
```

2023-11-14 08:43 UTC, Eikix commented on crates/utils/src/eth_transaction.cairo
> +        param: TransactionMetadata, encoded_tx_data: Span<u8>
will have to change throughout the function as well^^

2023-11-14 08:44 UTC, Eikix requested changes
oops, one typo,
can you activate cspell if it's not already activated?
chances are it can't catch these enum names typo, but in case

2023-11-14 10:58 UTC, bajpai244 commented on crates/utils/src/eth_transaction.cairo
> +
Oh! Makes sense, I forgot that we use starknet gas directly!

2023-11-14 11:03 UTC, bajpai244 commented on crates/utils/src/eth_transaction.cairo
> +            return Result::Err(EthTransactionError::IncoorectChainId);
fixed via [this](https://github.com/kkrt-labs/kakarot-ssj/pull/536/commits/2ab54973cd51818841cbaf4cf8efaf0400855ac3) commit.

2023-11-14 11:04 UTC, bajpai244 commented on crates/utils/src/eth_transaction.cairo
> +        param: TransactionMetadata, encoded_tx_data: Span<u8>
fixed via [this](https://github.com/kkrt-labs/kakarot-ssj/pull/536/commits/c3c6bffc210cb384edd58631cd4633f4bd8f09c3) commit.

2023-11-14 11:05 UTC, bajpai244 commented
> oops, one typo, can you activate cspell if it's not already activated? chances are it can't catch these enum names typo, but in case

Gotcha, will looks into the extension as well :)

2023-11-14 11:25 UTC, Eikix approved these changes
lgtm

2023-11-14 11:25 UTC, merged