feat: chain_id in eao
kkrt-labs/kakarot-ssj pull request #547
Opened 2023-11-17 12:53 UTC by chachaleo

## Pull Request type

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Resolves: #475

2023-11-17 13:10 UTC, enitrat commented on crates/contracts/src/tests/test_eoa.cairo
> +        let account_class_hash = kakarot_state.account_class_hash();
don't use this class hash, use `UninitializedAccount::TEST_CLASS_HASH.try_into().unwrap()`. you don't need the line above

2023-11-17 13:10 UTC, enitrat commented on crates/contracts/src/tests/test_eoa.cairo
> +        let maybe_address = deploy_syscall(account_class_hash, evm_address.into(), calldata, false);
```suggestion
        let starknet_address = deploy_syscall(account_class_hash, evm_address.into(), calldata, false).expect('failed to deploy EOA');
```

2023-11-17 13:10 UTC, enitrat commented on crates/contracts/src/tests/test_eoa.cairo
> +                account.initialize(kakarot_state.eoa_class_hash());
```suggestion
                account.initialize(ExternallyOwnedAccount::TEST_CLASS_HASH.try_into().unwrap());
```

2023-11-17 13:10 UTC, enitrat commented on crates/contracts/src/tests/test_eoa.cairo
> +        let calldata: Span<felt252> = array![kakarot_address.into(), evm_address.into()].span();
This previously was 
`[kakarot_address().into(), eoa_address().into()].span();`
Let's keep it the same

2023-11-20 08:58 UTC, enitrat submitted a review, later dismissed
lgtm

2023-11-20 09:04 UTC, Eikix commented on crates/contracts/src/tests/test_eoa.cairo
> +    fn deploy_eoa(kakarot_address: ContractAddress) -> IExternallyOwnedAccountDispatcher {
I think we should rather pass an eoa address so that we can call multiple times this util in case we want to deploy two or three eoas.

The signature would become:
```suggestion
    fn deploy_eoa(eoa_address: EthAddress) -> IExternallyOwnedAccountDispatcher {
```

You'd change the calldata to have the eoa_address arg.
And replace set_contract_address(kakarot_address) by 
let kakarot_address = get_contract_address();

Since usually we set_contract_address(kakarot_address) beforehand.

2023-11-20 09:04 UTC, Eikix requested changes
smol quality of life change requested:)! nice PR!

2023-11-20 09:26 UTC, enitrat approved these changes

2023-11-20 09:50 UTC, Eikix approved these changes
big! gg!

2023-11-20 09:50 UTC, merged