refactor: call opcodes
kkrt-labs/kakarot-ssj pull request #648
Opened 2023-12-11 14:38 UTC by enitrat

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Resolves: #645 #647 

## What is the new behavior?

- Refactored call opcodes by deleting prepare_call 
- Added message_call gas accounting
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

2023-12-12 14:03 UTC, bajpai244 commented on crates/evm/src/call_helpers.cairo
> +    fn generic_call(
We should use naming of variables as per ELS wherever possible.

<img width="363" alt="image" src="https://github.com/kkrt-labs/kakarot-ssj/assets/41180869/007eedb6-db6f-4796-a096-24d9edb49a0b">

2023-12-12 14:05 UTC, bajpai244 commented on crates/evm/src/call_helpers.cairo
>          // Case 2: `to` address is not a precompile
Is this comment correctly placed?

2023-12-12 14:27 UTC, enitrat commented on crates/evm/src/call_helpers.cairo
> +    fn generic_call(
I don't necessarily agree, if they make sense yes, but in these case ours carry more semantics

2023-12-12 14:53 UTC, bajpai244 commented on crates/evm/src/call_helpers.cairo
> +            caller: caller,
we can just do:
`caller,`

2023-12-12 14:53 UTC, bajpai244 commented on crates/evm/src/call_helpers.cairo
>              code: code,
same here:

`code,`

2023-12-12 14:53 UTC, bajpai244 commented on crates/evm/src/instructions/system_operations.cairo
> +        let args_offset = self.stack.pop_usize()?;
can be a different issue, but probably we should look to have variable names as close to ELS.

<img width="552" alt="image" src="https://github.com/kkrt-labs/kakarot-ssj/assets/41180869/54e52475-8b61-4028-8201-ebecf75b5dd3">

2023-12-12 14:53 UTC, bajpai244 commented on crates/evm/src/instructions/system_operations.cairo
> +        let max_memory_size = if args_max_offset > ret_max_offset {
we can create a seperate issue for this, to model our memory extension gas function to be similar to ELS.

i.e, the function itself can abstract away the logic of figuring out the max memory expansion.
<img width="604" alt="image" src="https://github.com/kkrt-labs/kakarot-ssj/assets/41180869/9c232543-fe0c-4685-a6f7-599d5909d0f1">

2023-12-12 14:53 UTC, bajpai244 commented on crates/evm/src/tests/test_call_helpers.cairo
I think we will need replacements for these tests, and I guess we would need them in this PR itself to make sure that we are passing the expected behaviour.

2023-12-12 15:37 UTC, bajpai244 commented on crates/evm/src/call_helpers.cairo
> +    fn generic_call(
Hmm, I guess something we can discuss later on, but I feel the closer we are to the ELS, the better.

2023-12-12 23:19 UTC, enitrat reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/648)* status: 0 of 6 files reviewed, 7 unresolved discussions (waiting on @bajpai244 and @ClementWalter)

___
*[`crates/evm/src/call_helpers.cairo` line 52 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/648#gh-1424039289:-NlVJcs92uHXp2RMVu7Q:b-r063gf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/f59341c38875053f5c8d91261ba1239004b53400/crates/evm/src/call_helpers.cairo#L52)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

Hmm, I guess something we can discuss later on, but I feel the closer we are to the ELS, the better.
</blockquote></details>

EELS is poorly designed in a lot of places!
___
*[`crates/evm/src/call_helpers.cairo` line 75 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/648#gh-1424041777:-NlVJfYuBjQ8Peu1dci7:ba3dfob) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/f59341c38875053f5c8d91261ba1239004b53400/crates/evm/src/call_helpers.cairo#L75)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

Is this comment correctly placed?
</blockquote></details>

Removed
___
*[`crates/evm/src/instructions/system_operations.cairo` line 36 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/648#gh-1424098121:-NlVJlAs09wR-YF4dArM:b-j5e57o) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/ad2645676df4a1eb66ac7e19cac73fedccf853d9/crates/evm/src/instructions/system_operations.cairo#L36)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

can be a different issue, but probably we should look to have variable names as close to ELS.

<img width="552" alt="image" src="https://github.com/kkrt-labs/kakarot-ssj/assets/41180869/54e52475-8b61-4028-8201-ebecf75b5dd3">

</blockquote></details>

same answer as above
___
*[`crates/evm/src/instructions/system_operations.cairo` line 140 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/648#gh-1424110007:-NlVJo4d1eDJm_4qlCin:b7h4g8y) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/ad2645676df4a1eb66ac7e19cac73fedccf853d9/crates/evm/src/instructions/system_operations.cairo#L140)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

we can create a seperate issue for this, to model our memory extension gas function to be similar to ELS.

i.e, the function itself can abstract away the logic of figuring out the max memory expansion.
<img width="604" alt="image" src="https://github.com/kkrt-labs/kakarot-ssj/assets/41180869/9c232543-fe0c-4685-a6f7-599d5909d0f1">

</blockquote></details>

Not adapted to Cairo - creating a List of Tuple is overkill
___
*[`crates/evm/src/tests/test_call_helpers.cairo` line 0 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/648#gh-1424116431:-NlVJu4XAlaxp5zZZxVR:b6n50t8) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/ad2645676df4a1eb66ac7e19cac73fedccf853d9/crates/evm/src/tests/test_call_helpers.cairo#L0)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

I think we will need replacements for these tests, and I guess we would need them in this PR itself to make sure that we are passing the expected behaviour.
</blockquote></details>

Discussed internally - we will rely on EF-Tests mostly. If we want to increase coverage we could eventually add internal functions to test the preparation of the generic call


<!-- Sent from Reviewable.io -->

2023-12-13 04:43 UTC, bajpai244 approved these changes
LGTM 🚀

2023-12-13 04:43 UTC, bajpai244 requested changes
@enitrat the tests are failing, we have to make them pass before we can merge.

2023-12-13 15:23 UTC, bajpai244 approved these changes

2023-12-13 15:39 UTC, merged