feat: blake 2 precompile
kkrt-labs/kakarot-ssj pull request #694
Opened 2024-01-05 12:33 UTC by bajpai244

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

This PR adds support for blake 2 precompile.

Resolves: #662 

## What is the new behavior?

Support for Blake-2 precompile is added.

## Resources used

The following resources were used to prepare this pr:
- [EIP-152](https://eips.ethereum.org/EIPS/eip-152)
- [Wikipidea](https://en.wikipedia.org/wiki/BLAKE_(hash_function)
- [revm](https://github.com/bluealloy/revm/blob/main/crates/precompile/src/blake2.rs)
- [spec](https://datatracker.ietf.org/doc/html/rfc7693#section-1)

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2024-01-05 14:36 UTC, enitrat requested changes
Great!

> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-:-NnP2UzzD9-Nbn_ixY6J:btojbfd)* status: all files reviewed, 18 unresolved discussions (waiting on @bajpai244 and @ClementWalter)

___
*[`crates/alexandria_math/Scarb.toml` line 8 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnOwhcP3TeXSgBwBMdZ:-NnOwhcP3TeXSgBwBMd_:b4qpjr8) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/alexandria_math/Scarb.toml#L8)):*
> ```TOML
> 
> [dependencies]
> alexandria_storage = { path = "../alexandria_storage" }
> ```

what for? alexandria storage is used for starknet storage
___
*[`crates/alexandria_math/src/blake2_compress.cairo` line 0 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnOx1NI1B1gxTKzA3AQ:-NnOx1NI1B1gxTKzA3AR:b-ty4dkr) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/alexandria_math/src/blake2_compress.cairo#L0)):*
I think we should have this internally and not in Alexandria. There is a very high probability that no one will ever use blake2f on starknet, given that it's super inefficient compared to the natively provided hash functions and it adds overhead in the maintenance of the library.

(especially considering that even in the EVM its usage is questioned https://ethereum-magicians.org/t/discussion-removal-of-ripemd-160-and-blake2f-precompiles/14857)
___
*[`crates/alexandria_math/src/blake2_compress.cairo` line 42 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnOtoA8Ew2JVcKz9nf8:-NnOtoA8Ew2JVcKz9nf9:bosy3z3) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/alexandria_math/src/blake2_compress.cairo#L42)):*
> ```Cairo
>         value // No rotation needed
>     } else {
>         let bits = 64; // The number of bits in a u64
> ```

you can use the core::num::traits::BitSize traits to get the number of bits in a type

e.g 
```rust
use core::num::traits::BitSize;

#[test]
fn test_bit_size() {
    assert!(BitSize::<u8>::bits() == 8);
    assert!(BitSize::<u16>::bits() == 16);
    assert!(BitSize::<u32>::bits() == 32);
    assert!(BitSize::<u64>::bits() == 64);
    assert!(BitSize::<u128>::bits() == 128);
    assert!(BitSize::<u256>::bits() == 256);
    assert!(BitSize::<i8>::bits() == 8);
    assert!(BitSize::<i16>::bits() == 16);
    assert!(BitSize::<i32>::bits() == 32);
    assert!(BitSize::<i64>::bits() == 64);
    assert!(BitSize::<i128>::bits() == 128);
    assert!(BitSize::<bytes31>::bits() == 248);
}
```
___
*[`crates/alexandria_math/src/blake2_compress.cairo` line 89 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnOvF6J4dYOQbLl2BN0:-NnOvF6J4dYOQbLl2BN1:birskb7) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/alexandria_math/src/blake2_compress.cairo#L89)):*
> ```Cairo
> 
>     if f {
>         v.set(14, U64BitNot::bitnot((v[14])));
> ```

BitNot operator is `~`



_Code quote:_
```Cairo
 U64BitNot
```
___
*[`crates/alexandria_storage/src/lib.cairo` line 2 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnOxoIg2Od2b-10cDzK:-NnOxoIg2Od2b-10cDzL:ba68ybp) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/alexandria_storage/src/lib.cairo#L2)):*
> ```Cairo
> mod list;
> mod vec;
> ```

Should be in an alexandria_data_structures crate, not alexandria_storage
___
*[`crates/evm/src/errors.cairo` line 67 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnOxywDBsLff6GOmMSv:-NnOxywDBsLff6GOmMSw:b5bhgn9) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/evm/src/errors.cairo#L67)):*
> ```Cairo
>     Assertion,
>     DepthLimit,
>     PrecompileError: PrecompileError
> ```

is there such thing as a PrecompileError in the EVM? I wouldn't introduce errors that are  not in the spec or in common clients. If the error is an input error I think it can fall under the `InvalidParameter` error (from exec-specs)
___
*[`crates/evm/src/precompiles.cairo` line 1 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnOyI811gRVOJ9bjlZF:-NnOyI811gRVOJ9bjlZG:b-7t5gcf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/evm/src/precompiles.cairo#L1)):*
> ```Cairo
> mod blake2;
> ```

I think the _precompile_ itself is implements only the compression function `F` used in the BLAKE2 cryptographic primitive, so this should be `mod blake2f;`
___
*[`crates/evm/src/precompiles/blake2.cairo` line 25 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnOz-m86c5oI4iIzHzp:-NnOz-m86c5oI4iIzHzq:b4zwrhx) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/evm/src/precompiles/blake2.cairo#L25)):*
> ```Cairo
>         let input = input.span();
> 
>         if input.len() != INPUT_LENGTH {
> ```

you can use the `ensure` function for that. I think we should follow the execution specs on this for the error type.
this would simply become:

`ensure(input.len() == INPUT_LENGTH, EVMError::InvalidParameter)?;`
___
*[`crates/evm/src/precompiles/blake2.cairo` line 29 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnOzi9V6Rex2L7uUo_2:-NnOzi9V6Rex2L7uUo_3:b-xkmlg9) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/evm/src/precompiles/blake2.cairo#L29)):*
> ```Cairo
>         };
> 
>         let f = match (*input[212]).into() {
> ```

nice to use a match statement! This will apparently become more optimized in future cairo versions then if-elses.
___
*[`crates/evm/src/precompiles/blake2.cairo` line 34 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnOzgwEBc87HESa9JL6:-NnOzgwEBc87HESa9JL7:b-gzj7aq) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/evm/src/precompiles/blake2.cairo#L34)):*
> ```Cairo
>             _ => {
>                 return Result::Err(
>                     EVMError::PrecompileError(PrecompileError::Blake2WrongFinalIndicatorFlag)
> ```

same as previous remark about errors
___
*[`crates/evm/src/precompiles/blake2.cairo` line 39 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnP-DKU-bMIPTPZUG4T:-NnP-DKU-bMIPTPZUG4U:b45h) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/evm/src/precompiles/blake2.cairo#L39)):*
> ```Cairo
>         };
> 
>         let rounds = match U32Trait::from_be_bytes(input.slice(0, 4)) {
> ```





_Suggestion:_
```Cairo
let rounds = U32Trait::from_be_bytes(input.slice(0, 4)).ok_or(EVMError::TypeConversionError('extraction of u32 failed'))?;
```
___
*[`crates/evm/src/precompiles/blake2.cairo` line 48 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnP-Zrm8oc1m35kfkDj:-NnP-Zrm8oc1m35kfkDk:b-twe4pz) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/evm/src/precompiles/blake2.cairo#L48)):*
> ```Cairo
>         let gas: u128 = (GF_ROUND * rounds.into()).into();
> 
>         if (gas > vm.gas_left()) {
> ```

this is redundant as if the gas is more than the gas left, the  `vm.charge_gas(gas)?;` will return an error
___
*[`crates/evm/src/precompiles/blake2.cairo` line 64 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnP-izbEtD5gm4ysaTJ:-NnP-izbEtD5gm4ysaTK:bxuvs9a) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/evm/src/precompiles/blake2.cairo#L64)):*
> ```Cairo
>             }
> 
>             h.append(U64Trait::from_le_bytes(input.slice(pos, 8)).unwrap());
> ```

is it a safe unwrap? (also please check the next unwraps)
___
*[`crates/utils/src/helpers.cairo` lin [...]

2024-01-08 05:07 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694)* status: 16 of 24 files reviewed, 18 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/alexandria_math/Scarb.toml` line 8 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnOwhcP3TeXSgBwBMdZ:-NnbPxXF0ylrao77f4F9:bx8mwn7) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/alexandria_math/Scarb.toml#L8)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

what for? alexandria storage is used for starknet storage
</blockquote></details>

We are using vectors, and the code for the same relies in that crate.
___
*[`crates/alexandria_math/src/blake2_compress.cairo` line  at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnOx1NI1B1gxTKzA3AQ:-NnbQ6p45vQEuabKKWpK:b-sj2s8y) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/alexandria_math/src/blake2_compress.cairo#L)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

I think we should have this internally and not in Alexandria. There is a very high probability that no one will ever use blake2f on starknet, given that it's super inefficient compared to the natively provided hash functions and it adds overhead in the maintenance of the library.

(especially considering that even in the EVM its usage is questioned https://ethereum-magicians.org/t/discussion-removal-of-ripemd-160-and-blake2f-precompiles/14857)
</blockquote></details>

Gotcha, moving it to utils then, making a module called `crypto` inside it, and we can put all other crypto stuff that we implement there.


<!-- Sent from Reviewable.io -->

2024-01-08 05:17 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694)* status: 16 of 24 files reviewed, 18 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/alexandria_storage/src/lib.cairo` line 2 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnOxoIg2Od2b-10cDzK:-NnbT13N4XLd8fxdtFqt:b-okirq6) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/alexandria_storage/src/lib.cairo#L2)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Should be in an alexandria_data_structures crate, not alexandria_storage
</blockquote></details>

gotcha! Done!

Although technically list is also a data structure, so I thought keeping it in storage made sense, rather than making a new crate for adding this.

But I have refactored accordingly!
___
*[`crates/evm/src/errors.cairo` line 67 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnOxywDBsLff6GOmMSv:-NnbV59b0nT79-TqiISj:bcbgg9s) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/evm/src/errors.cairo#L67)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

is there such thing as a PrecompileError in the EVM? I wouldn't introduce errors that are  not in the spec or in common clients. If the error is an input error I think it can fall under the `InvalidParameter` error (from exec-specs)
</blockquote></details>

Makes sense, I followed the revm approach, which makes it very easy to do error handling, but according to the specs, the error is simply InvalidParameter! 

Pivoting to it!


<!-- Sent from Reviewable.io -->

2024-01-08 05:29 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694)* status: 14 of 28 files reviewed, 18 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/evm/src/errors.cairo` line 67 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnOxywDBsLff6GOmMSv:-NnbXc6hA51c81WL_t3V:b-896fja) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/evm/src/errors.cairo#L67)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

Makes sense, I followed the revm approach, which makes it very easy to do error handling, but according to the specs, the error is simply InvalidParameter! 

Pivoting to it!
</blockquote></details>

Done!


<!-- Sent from Reviewable.io -->

2024-01-08 05:34 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694)* status: 12 of 28 files reviewed, 18 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/evm/src/precompiles.cairo` line 1 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnOyI811gRVOJ9bjlZF:-NnbYfzD2JK_Uh-rEqZ4:boj7l8d) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/evm/src/precompiles.cairo#L1)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

I think the _precompile_ itself is implements only the compression function `F` used in the BLAKE2 cryptographic primitive, so this should be `mod blake2f;`
</blockquote></details>

makes sense, done!
___
*[`crates/evm/src/precompiles/blake2.cairo` line 29 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnOzi9V6Rex2L7uUo_2:-NnbYlsW2yjo0IcPIl1X:bep82em) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/evm/src/precompiles/blake2.cairo#L29)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

nice to use a match statement! This will apparently become more optimized in future cairo versions then if-elses.
</blockquote></details>

Yeah, although I think that firstly the requirement of doing all match cases in order would have to be removed! Otherwise imagine, if u all u care about is case 1 and 243, now you have to manually write cases for 0, and 2...242!
___
*[`crates/evm/src/precompiles/blake2.cairo` line 34 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnOzgwEBc87HESa9JL6:-NnbZ-nk9Sq-oEAOl-8d:b6p80ey) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/evm/src/precompiles/blake2.cairo#L34)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

same as previous remark about errors
</blockquote></details>

removed! 


<!-- Sent from Reviewable.io -->

2024-01-08 05:37 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694)* status: 9 of 28 files reviewed, 18 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/evm/src/precompiles/blake2.cairo` line 25 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnOz-m86c5oI4iIzHzp:-NnbZuk_5Vxxb-u7zJy7:b-7rl0jq) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/evm/src/precompiles/blake2.cairo#L25)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

you can use the `ensure` function for that. I think we should follow the execution specs on this for the error type.
this would simply become:

`ensure(input.len() == INPUT_LENGTH, EVMError::InvalidParameter)?;`
</blockquote></details>

done!


<!-- Sent from Reviewable.io -->

2024-01-08 05:40 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694)* status: 9 of 28 files reviewed, 18 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/evm/src/precompiles/blake2.cairo` line 39 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnP-DKU-bMIPTPZUG4T:-Nnb__Ho8_QaQswLoHwA:b-896fix) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/evm/src/precompiles/blake2.cairo#L39)):*
> ```Cairo
>         };
> 
>         let rounds = match U32Trait::from_be_bytes(input.slice(0, 4)) {
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-01-08 05:43 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694)* status: 9 of 28 files reviewed, 18 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/evm/src/precompiles/blake2.cairo` line 48 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnP-Zrm8oc1m35kfkDj:-NnbaBxM6pD3k4zExT9A:blcls5a) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/evm/src/precompiles/blake2.cairo#L48)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

this is redundant as if the gas is more than the gas left, the  `vm.charge_gas(gas)?;` will return an error
</blockquote></details>

just realized this, removed for other precompiles as well!


<!-- Sent from Reviewable.io -->

2024-01-08 05:46 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694)* status: 8 of 30 files reviewed, 18 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/evm/src/precompiles/blake2.cairo` line 64 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnP-izbEtD5gm4ysaTJ:-NnbatZv6jeOifTVUos9:b6th0u2) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/evm/src/precompiles/blake2.cairo#L64)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

is it a safe unwrap? (also please check the next unwraps)
</blockquote></details>

yes, they are safe, added comments to explain why they are safe. 


<!-- Sent from Reviewable.io -->

2024-01-08 05:58 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694)* status: 8 of 30 files reviewed, 18 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/helpers.cairo` line 688 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnP0RvR-Sb93CvTtMI3:-NnbdPjB5QEHpe-nFKu0:b-f96qda) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/utils/src/helpers.cairo#L688)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

can we start at i = len-1, decrement i  until 0 instead? saves us two substractions (len-1) - i and (offset - i) I think
</blockquote></details>

can u explain more how will it save subtractions?

Because, if we start with i = len -1, then shift for the corressponding byte will be stored at  `i - (len - 1)` and in that sense, we are still doing two substractions.


<!-- Sent from Reviewable.io -->

2024-01-08 06:03 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694)* status: 8 of 30 files reviewed, 18 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/helpers.cairo` line 792 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnP153Y-naNS-5njlEf:-Nnbdmu50Lmg-xtAIUVB:b-xps2x0) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/utils/src/helpers.cairo#L792)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

You're not using the same logic as for u32 - which one is the most efficient?
</blockquote></details>

I took the approach that already existed in the module, i.e logic was different for u32 and u64, u128, etc for the already existing `be` methods.

So, I just followed the same approach as of now, where for `le` methods, I took the corressponding be implementation, and took them!

*Now, as per which is more efficient.*

I think the one on u32 must be more, as we are caching the shifts for all bytes, rather than calculating it as done in other cases.

+ I also think we should make a separate issue to explore the differences, and significant difference are there, then to refactor this for the whole mod.


<!-- Sent from Reviewable.io -->

2024-01-08 06:04 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694)* status: 8 of 30 files reviewed, 18 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/math.cairo` line 104 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnP29VT7m6yzYW44RFW:-Nnbf0-F0dftLMrwdOX4:b5glgcp) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/utils/src/math.cairo#L104)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Where is this used?
</blockquote></details>

used in `wrapping_shl` for u64.
___
*[`crates/utils/src/math.cairo` line 354 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnP1cQE7r6fSSoB0C4N:-Nnbf3S02Qz7gvQRjGYF:b-1bjpmn) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/utils/src/math.cairo#L354)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

nice
</blockquote></details>

thanks :)


<!-- Sent from Reviewable.io -->

2024-01-08 06:14 UTC, bajpai244 reviewed
Thanks :)

> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-:-NnbhAP79qNCV6Ruv3HK:bvtk9y9)* status: 8 of 30 files reviewed, 18 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/math.cairo` line 364 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnP1rXRCxMQ7QCoXqkT:-Nnbfn0Z3zFTwhXkzJHK:b-bydhfv) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/utils/src/math.cairo#L364)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

SW defined it in `core::keccak::u128_split` as:

fn u128_split(input: u128) -> (u64, u64) {
    let (high, low) = core::integer::u128_safe_divmod(
        input, 0x10000000000000000_u128.try_into().unwrap()
    );

    (u128_to_u64(high), u128_to_u64(low))
}
</blockquote></details>

gotcha, now using the implementation from the core lib.
___
*[`crates/alexandria_math/src/blake2_compress.cairo` line 42 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnOtoA8Ew2JVcKz9nf8:-NnbgMkE9Xth5fORu9Ey:boj7l8d) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/alexandria_math/src/blake2_compress.cairo#L42)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

you can use the core::num::traits::BitSize traits to get the number of bits in a type

e.g 
```rust
use core::num::traits::BitSize;

#[test]
fn test_bit_size() {
    assert!(BitSize::<u8>::bits() == 8);
    assert!(BitSize::<u16>::bits() == 16);
    assert!(BitSize::<u32>::bits() == 32);
    assert!(BitSize::<u64>::bits() == 64);
    assert!(BitSize::<u128>::bits() == 128);
    assert!(BitSize::<u256>::bits() == 256);
    assert!(BitSize::<i8>::bits() == 8);
    assert!(BitSize::<i16>::bits() == 16);
    assert!(BitSize::<i32>::bits() == 32);
    assert!(BitSize::<i64>::bits() == 64);
    assert!(BitSize::<i128>::bits() == 128);
    assert!(BitSize::<bytes31>::bits() == 248);
}
```
</blockquote></details>

makes sense, done!
___
*[`crates/alexandria_math/src/blake2_compress.cairo` line 89 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnOvF6J4dYOQbLl2BN0:-Nnbh-SP-MzZUyzQA8Y1:b-pked2i) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/alexandria_math/src/blake2_compress.cairo#L89)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

BitNot operator is `~`
</blockquote></details>

Intersting, we need to add this to the cairo book then -> https://book.cairo-lang.org/appendix-02-operators-and-symbols.html

Will make a PR :)


<!-- Sent from Reviewable.io -->

2024-01-08 10:44 UTC, enitrat approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 8 files at r2, 7 of 8 files at r3, 1 of 3 files at r4, 4 of 5 files at r5, 3 of 4 files at r8, 1 of 1 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-:-Nncf9aI5J2-FWN0itOF:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @bajpai244 and @ClementWalter)

___
*[`crates/utils/src/helpers.cairo` line 792 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnP153Y-naNS-5njlEf:-NncenSPAdjwBeQMr0ov:bpyfd1j) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/utils/src/helpers.cairo#L792)):*
> I also think we should make a separate issue to explore the differences, and significant difference are there, then to refactor this for the whole mod.

Let's do this!
___
*[`crates/alexandria_storage/src/lib.cairo` line 2 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnOxoIg2Od2b-10cDzK:-Nncf-MX-qXliUFfGkJN:b-7uld1c) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/alexandria_storage/src/lib.cairo#L2)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

gotcha! Done!

Although technically list is also a data structure, so I thought keeping it in storage made sense, rather than making a new crate for adding this.

But I have refactored accordingly!
</blockquote></details>

Well, not really! List is not a data structure: it's just an interface that allows you to interact with storage with methods that simulate the behavior of a list. It's not an actual DS.
___
*[`crates/alexandria_math/src/blake2_compress.cairo` line 89 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnOvF6J4dYOQbLl2BN0:-NncexwyDZ4qbBOXf1WT:b-7s4s8d) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/alexandria_math/src/blake2_compress.cairo#L89)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

Intersting, we need to add this to the cairo book then -> https://book.cairo-lang.org/appendix-02-operators-and-symbols.html

Will make a PR :)
</blockquote></details>

cool!
___
*[`crates/evm/src/precompiles/blake2.cairo` line 29 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/694#-NnOzi9V6Rex2L7uUo_2:-NnceSxEAr-N4bEqBI5r:bsu11jy) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/dc17ef25a419794e9fd40a6cafe3d3c7bcc368fd/crates/evm/src/precompiles/blake2.cairo#L29)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

Yeah, although I think that firstly the requirement of doing all match cases in order would have to be removed! Otherwise imagine, if u all u care about is case 1 and 243, now you have to manually write cases for 0, and 2...242!
</blockquote></details>

I think it's coming in 2.5


<!-- Sent from Reviewable.io -->

2024-01-09 06:15 UTC, merged