feat: add math helpers required for #699 { modexp precompile }
kkrt-labs/kakarot-ssj pull request #703
Opened 2024-01-19 08:36 UTC by bajpai244

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Adds all maths utils required by #699.

Resolves: #702 

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2024-01-19 09:17 UTC, enitrat requested changes
Generally I think we can probably divide the number of logic lines (excluding "boilerplate lines") by three by making all of these generic. Think about composition: if you're defining the same function for mulitple types, then you can group them under a trait. If you have correctly written traits required for the operation performed, than you can make one _single_ generic impl for this trait with restrictions on the generic type - and you save yourself tons of code repetition

> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-:-NoW-IDn-T30TWS3Zk5d:b1xnckf)* status: 1 of 2 files reviewed, 8 unresolved discussions (waiting on @bajpai244 and @ClementWalter)

___
*[`crates/utils/src/math.cairo` line 69 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoVvEyXEmnx19HqymJs:-NoVvEyXEmnx19HqymJt:b9iycp0) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/937ffe68d34e5b1c0daaa7d3661414f87a5e7031/crates/utils/src/math.cairo#L69)):*
> ```Cairo
>     use super::u8_overflowing_mul;
> 
>     fn wrapping_spow(base: u8, exponent: u8) -> u8 {
> ```

this looks like a generic behavior for multiple types (u8, u32, u128, u256, etc). With only two implementations previously it might not have been worth it, but now I think you put these functions inside the `WrappingExponentiation` trait and implement the behavior of `wrapping_fpow` and `wrapping_spow` generically
___
*[`crates/utils/src/math.cairo` line 387 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoVxIi562ShI_Qjgi1f:-NoVxIi562ShI_Qjgi1g:undefined) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/937ffe68d34e5b1c0daaa7d3661414f87a5e7031/crates/utils/src/math.cairo#L387)):*
> ```Cairo
> }
> 
> impl u8WrappingBitshiftImpl of WrappingBitshift<u8> {
> ```





_Suggestion:_
```Cairo
U8WrappingBitshiftImpl
```
___
*[`crates/utils/src/math.cairo` line 388 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoVxVv3-Nfh5fe8GAiR:-NoVxVv3-Nfh5fe8GAiS:bbec5x6) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/937ffe68d34e5b1c0daaa7d3661414f87a5e7031/crates/utils/src/math.cairo#L388)):*
> ```Cairo
> 
> impl u8WrappingBitshiftImpl of WrappingBitshift<u8> {
>     fn wrapping_shl(self: u8, shift: u8) -> u8 {
> ```

can we make these impl generic as well?
___
*[`crates/utils/src/math.cairo` line 405 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoVxOmV-wCE4NeZEwf3:-NoVxOmV-wCE4NeZEwf4:undefined) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/937ffe68d34e5b1c0daaa7d3661414f87a5e7031/crates/utils/src/math.cairo#L405)):*
> ```Cairo
> }
> 
> impl u32WrappingBitshiftImpl of WrappingBitshift<u32> {
> ```





_Suggestion:_
```Cairo
U32WrappingBitshiftImpl
```
___
*[`crates/utils/src/math.cairo` line 449 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#gh-1458579764:-NoVy-DZ4KKhd_tecjlA:b-ta1bxd) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/937ffe68d34e5b1c0daaa7d3661414f87a5e7031/crates/utils/src/math.cairo#L449)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

@enitrat can u explain me this comment in some detail?
</blockquote></details>

if you take the binary value MAX_U128 (0xFFF...FFF) and shift it by 127 bits to the right, the remaining value is `0b1`.
If you shift it by 128 it is `0b0`
___
*[`crates/utils/src/math.cairo` line 522 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoW-4PnE7kinoEpakcp:-NoW-4PnE7kinoEpakcq:b-5frd37) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/937ffe68d34e5b1c0daaa7d3661414f87a5e7031/crates/utils/src/math.cairo#L522)):*
> ```Cairo
> /// any overflow is discarded
> fn u32_overflowing_mul(lhs: u32, rhs: u32) -> (u32, bool) {
>     let result = u32_wide_mul(lhs, rhs);
> ```

Create a generic trait for this, so by combining with the comments below you can make a generic implementation for OverflowingMul
___
*[`crates/utils/src/math.cairo` line 524 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoVzpwF24jGBA-VlTr9:-NoVzpwF24jGBA-VlTrA:b-96ip6y) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/937ffe68d34e5b1c0daaa7d3661414f87a5e7031/crates/utils/src/math.cairo#L524)):*
> ```Cairo
>     let result = u32_wide_mul(lhs, rhs);
> 
>     let mask = 0xFFFFFFFF;
> ```

BoundedInt::<u32>::max()
___
*[`crates/utils/src/math.cairo` line 525 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoVzyDcEVHY5cAwvKuO:-NoVzyDcEVHY5cAwvKuP:bz2lmuc) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/937ffe68d34e5b1c0daaa7d3661414f87a5e7031/crates/utils/src/math.cairo#L525)):*
> ```Cairo
> 
>     let mask = 0xFFFFFFFF;
>     let top_word: u32 = (result.shr(32) & mask).try_into().unwrap();
> ```

BitSize::<u32>::bits()



_Code quote:_
```Cairo
32
```


<!-- Sent from Reviewable.io -->

2024-01-19 11:59 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703)* status: 1 of 2 files reviewed, 8 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/math.cairo` line 449 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#gh-1458579764:-NoWZ3mV3MgVChCy4CzF:buifue7) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/937ffe68d34e5b1c0daaa7d3661414f87a5e7031/crates/utils/src/math.cairo#L449)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

if you take the binary value MAX_U128 (0xFFF...FFF) and shift it by 127 bits to the right, the remaining value is `0b1`.
If you shift it by 128 it is `0b0`
</blockquote></details>

Oh, gotcha!
___
*[`crates/utils/src/math.cairo` line 522 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoW-4PnE7kinoEpakcp:-NoW_gYHBC52pGPRlTqE:bi9eqp2) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/937ffe68d34e5b1c0daaa7d3661414f87a5e7031/crates/utils/src/math.cairo#L522)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Create a generic trait for this, so by combining with the comments below you can make a generic implementation for OverflowingMul
</blockquote></details>

for that we also need a generic implementation of wide_mul as well right?


<!-- Sent from Reviewable.io -->

2024-01-19 12:12 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703)* status: 1 of 2 files reviewed, 8 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/math.cairo` line 387 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoVxIi562ShI_Qjgi1f:-NoWcZAH1bQDDmg2-6_P:b9jlx3d) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/937ffe68d34e5b1c0daaa7d3661414f87a5e7031/crates/utils/src/math.cairo#L387)):*
> ```Cairo
> }
> 
> impl u8WrappingBitshiftImpl of WrappingBitshift<u8> {
> ```

shouldn't traits generally start with a capital?


<!-- Sent from Reviewable.io -->

2024-01-19 13:01 UTC, bajpai244 commented
@enitrat I have implemented generics!

2024-01-19 15:47 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703)* status: 0 of 2 files reviewed, 10 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/math.cairo` line 69 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoVvEyXEmnx19HqymJs:-NoXM9ih5gs5uy-4j1fg:b-896fix) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/937ffe68d34e5b1c0daaa7d3661414f87a5e7031/crates/utils/src/math.cairo#L69)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

this looks like a generic behavior for multiple types (u8, u32, u128, u256, etc). With only two implementations previously it might not have been worth it, but now I think you put these functions inside the `WrappingExponentiation` trait and implement the behavior of `wrapping_fpow` and `wrapping_spow` generically
</blockquote></details>

Done.
___
*[`crates/utils/src/math.cairo` line 387 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoVxIi562ShI_Qjgi1f:-NoXMKZv8ZCgmugo9fZz:b-896fix) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/937ffe68d34e5b1c0daaa7d3661414f87a5e7031/crates/utils/src/math.cairo#L387)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

yeah, PascalCase
</blockquote></details>

Done.
___
*[`crates/utils/src/math.cairo` line 388 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoVxVv3-Nfh5fe8GAiR:-NoXMMy21kU0no4dd9jf:b-896fix) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/937ffe68d34e5b1c0daaa7d3661414f87a5e7031/crates/utils/src/math.cairo#L388)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

now it's possible to just define a generic impl for WrappingBitshift<T>, as overflowing_mul and wrapping_pow are generic
</blockquote></details>

Done.
___
*[`crates/utils/src/math.cairo` line 405 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoVxOmV-wCE4NeZEwf3:-NoXMNtuCfEMNl2H-luB:b-896fix) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/937ffe68d34e5b1c0daaa7d3661414f87a5e7031/crates/utils/src/math.cairo#L405)):*
> ```Cairo
> }
> 
> impl u32WrappingBitshiftImpl of WrappingBitshift<u32> {
> ```

Done.
___
*[`crates/utils/src/math.cairo` line 524 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoVzpwF24jGBA-VlTr9:-NoXMxuN6HsmTMBA-yw9:b-896fix) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/937ffe68d34e5b1c0daaa7d3661414f87a5e7031/crates/utils/src/math.cairo#L524)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

BoundedInt::<u32>::max()
</blockquote></details>

Done.
___
*[`crates/utils/src/math.cairo` line 525 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoVzyDcEVHY5cAwvKuO:-NoXOn2u5_RACLmgygIG:b-896fix) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/937ffe68d34e5b1c0daaa7d3661414f87a5e7031/crates/utils/src/math.cairo#L525)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

BitSize::<u32>::bits()
</blockquote></details>

Done.
___
*[`crates/utils/src/math.cairo` line 91 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoWpe3A9bfW8U6e_npf:-NoXMAW17u3IHPPqcPvv:bjqx6u4) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/847bf388f6f09a69e31058740962fe18aafe1286/crates/utils/src/math.cairo#L91)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

I guess we could do 10 * one ?
</blockquote></details>

You can't do that as there is not Ten trait!


<!-- Sent from Reviewable.io -->

2024-01-19 16:18 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703)* status: 0 of 2 files reviewed, 10 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/math.cairo` line 522 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoW-4PnE7kinoEpakcp:-NoXW6rX5CRtRdOhjRYx:b-896fix) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/937ffe68d34e5b1c0daaa7d3661414f87a5e7031/crates/utils/src/math.cairo#L522)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

yep - but only make this generic implementation accessible for types that do not already define a u_overflow_mul in the corelib (u128 and u256 do I think).
So typically you would write your generic impl inside a hidden module, use impl aliases to only make accessible the ones you want to use, as we've done in other parts of the codebase with`impl MyImpl = path::to::genericImpl<T>`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-19 16:44 UTC, enitrat requested changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703)* status: all files reviewed, 15 unresolved discussions (waiting on @bajpai244 and @ClementWalter)

___
*[`crates/utils/src/math.cairo` line 65 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoWplBS-l5bHW6p5JWG:-NoXWtTC66Elb4NsDnCB:b-kx8e2v) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/847bf388f6f09a69e31058740962fe18aafe1286/crates/utils/src/math.cairo#L65)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Needs one doc per function. (as an outside, what is spow? what is fpow?)
___
*[`crates/utils/src/math.cairo` line 91 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoWpe3A9bfW8U6e_npf:-NoXQexs7pM3a4bpt6QA:bj9z239) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/847bf388f6f09a69e31058740962fe18aafe1286/crates/utils/src/math.cairo#L91)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

You can't do that as there is not Ten trait!
</blockquote></details>

ah yes lol. quite bad that we cant have generic literals
___
*[`crates/utils/src/math.cairo` line 61 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXX852BbVA1fLTsyiS:-NoXX852BbVA1fLTsyiT:b-pgbxb4) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L61)):*
> ```Cairo
>     /// Raise a number to a power modulo MAX<T> (max value of type T).
>     /// Instead of explicitly providing a modulo, we use overflowing functions
>     /// from the core library, which wrap around when overflowing.
> ```

The function doc doesn't explain the process of separating <10 exponents and >= 10 exponents
___
*[`crates/utils/src/math.cairo` line 99 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXXG1k5UkQeEw_wPno:-NoXXG1k5UkQeEw_wPnp:b-9xuvre) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L99)):*
> ```Cairo
>     }
> 
>     /// this function performs exponentiation through a simple loop
> ```

Should respect rustdoc format and be in the trait definition
___
*[`crates/utils/src/math.cairo` line 115 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXXIoS1UzGKRhEclLc:-NoXXIoS1UzGKRhEclLd:b-51gjn2) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L115)):*
> ```Cairo
>     }
> 
>     /// this function performs exponentiation using binary exponentiation
> ```

Should respect rustdoc format and be in the trait definition. copilot chat is really good at creating function docs, I usually let it do the work
___
*[`crates/utils/src/math.cairo` line 121 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXYAbyBTt6Wr5fL9yi:-NoXYAbyBTt6Wr5fL9yj:bpqqj6t) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L121)):*
> ```Cairo
>         let mut exponent = exponent;
>         let two = One::<T>::one() + One::<T>::one();
> ```

Are you sure this implementation works for exponent=0? Please add a test.
___
*[`crates/utils/src/math.cairo` line 231 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXYVxp8i-Q8uJehYEk:-NoXYVxp8i-Q8uJehYEl:b-r1zj7t) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L231)):*
> ```Cairo
> 
> trait OverflowingMul<T> {
>     /// performs multiplication on a number, any overflow is discarded and boolean is returned indicating whether an overflow happened or not
> ```

Rustdoc-compliant format (copilot chat helps a lot)
___
*[`crates/utils/src/math.cairo` line 235 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXZ0kf-oeCB_5mY777:-NoXZ0kf-oeCB_5mY778:b-scepxq) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L235)):*
> ```Cairo
> }
> 
> impl u8OverflowingMul of OverflowingMul<u8> {
> ```

casing



_Code quote:_
```Cairo
u8
```
___
*[`crates/utils/src/math.cairo` line 240 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXZ33L5a-gV0_dRibB:-NoXZ33L5a-gV0_dRibC:b-o9fwoc) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L240)):*
> ```Cairo
>         let mask: u16 = BoundedInt::<u8>::max().into();
> 
>         let top_word: u8 = (result.shr(BitSize::<u8>::bits().try_into().unwrap()) & mask)
> ```

if you want to get the top word, why not masking with 0xFF00 instead ? here you're doing a lot of un-necessary operations
___
*[`crates/utils/src/math.cairo` line 245 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXZNC4DCXDk-ZeJQ1j:-NoXZNC4DCXDk-ZeJQ1k:b8g4l7) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L245)):*
> ```Cairo
>         let bottom_word = (result & mask).try_into().unwrap();
> 
>         match u8_to_felt252(top_word) {
> ```

I think this is just a complicated way of checking whether `result > U8_MAX`. You don't actually need the top word, it's just a condition to return a flag.
___
*[`crates/utils/src/math.cairo` line 252 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXZU_TDRtxy1AE1jot:-NoXZU_TDRtxy1AE1jou:b-scepxq) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L252)):*
> ```Cairo
> }
> 
> impl u32OverflowingMul of OverflowingMul<u32> {
> ```

casing



_Code quote:_
```Cairo
u32
```
___
*[`crates/utils/src/math.cairo` line 267 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXamkoERG7oPVE8n63:-NoXamkp2YjG-Z9nNrIg:b-scepxq) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L267)):*
> ```Cairo
> }
> 
> impl u64OverflowingMul of OverflowingMul<u64> {
> ```

casing



_Code quote:_
```Cairo
u64O
```
___
*[`crates/utils/src/math.cairo` line 279 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXalSy4-4EaLhzjt3m:-NoXalSy4-4EaLhzjt3n:b-scepxq) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L279)):*
> ```Cairo
> }
> 
> impl u128OverflowingMul of OverflowingMul<u128> {
> ```

casing



_Code quote:_
```Cairo
u128
```
___
*[`crates/utils/src/math.cairo` line 285 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXakMi7JXSh8H03Ks8:-NoXakMj-QjF1PjdSH2j:b-scepxq) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L285)):*
> ```Cairo
> }
> 
> impl u256OverflowingMul of OverflowingMul<u256> {
> ```

casing



_Code quote:_
```Cairo
u256
```
___
*[`crates/utils/src/math.cairo` line 293 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXabKiEgyM80lsJJzz:-NoXabKiEgyM80lsJK--:bm5loik) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L293)):*
> ```Cairo
> 
> trait WrappingMul<T> {
>     /// performs multiplication on a number, any overflow is discarded
> ```

Rustdoc compliant function doc - don't forget proper casing (a sentence starts with an uppercase letter)


<!-- Sent from Reviewable.io -->

2024-01-19 17:27 UTC, enitrat requested changes
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703)* status: 1 of 2 files reviewed, 18 unresolved discussions (waiting on @bajpai244 and @ClementWalter)

___
*[`crates/utils/src/math.cairo` line 74 at r7](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXkivM9L9j0iidXFuT:-NoXkivM9L9j0iidXFuU:undefined) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/f5cda99c5538ef861978c54f96224b3bef622159/crates/utils/src/math.cairo#L74)):*
> ```Cairo
>     /// a wrapping strategy to handle overflow. This means if intermediate or final results
>     /// overflow the type `T`, they will wrap around according to the rules defined for
>     /// the `wrapping_mul` method in Rust's standard library.
> ```





_Suggestion:_
```Cairo
    ///.
```
___
*[`crates/utils/src/math.cairo` line 90 at r7](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXkqz65rIAVDOLrQ66:-NoXkqz65rIAVDOLrQ67:b-jp9rti) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/f5cda99c5538ef861978c54f96224b3bef622159/crates/utils/src/math.cairo#L90)):*
> ```Cairo
>     ///   The result is wrapped in case of overflow.
>     ///
>     /// # Panics
> ```

Can be removed as it doesn't panic
___
*[`crates/utils/src/math.cairo` line 94 at r7](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXksKRB27C3aWbehIP:-NoXksKRB27C3aWbehIQ:bnpteg6) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/f5cda99c5538ef861978c54f96224b3bef622159/crates/utils/src/math.cairo#L94)):*
> ```Cairo
>     /// of type `T` can panic.
>     ///
>     /// # Safety
> ```

I don't think it's applicable here, we can remove the section


<!-- Sent from Reviewable.io -->

2024-01-19 17:36 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703)* status: 1 of 2 files reviewed, 18 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/math.cairo` line 65 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoWplBS-l5bHW6p5JWG:-NoXmIi-5Lb8LrOR9ks7:b8l51yx) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/847bf388f6f09a69e31058740962fe18aafe1286/crates/utils/src/math.cairo#L65)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Needs one doc per function. (as an outside, what is spow? what is fpow?)
</blockquote></details>

Yeah, it got ommitted by mistaked, now fixed.

spow uses a simple loop while fpow is binary exponentiation, I don't know why we use both of them in different conditions
___
*[`crates/utils/src/math.cairo` line 91 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoWpe3A9bfW8U6e_npf:-NoXmaYMDmVa0Cw8mvfP:b-4ty5m2) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/847bf388f6f09a69e31058740962fe18aafe1286/crates/utils/src/math.cairo#L91)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

ah yes lol. quite bad that we cant have generic literals
</blockquote></details>

lol! Yeah
___
*[`crates/utils/src/math.cairo` line 61 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXX852BbVA1fLTsyiS:-NoXm7KZ3Sy5WBJY8kIG:bvvfsdp) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L61)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

The function doc doesn't explain the process of separating <10 exponents and >= 10 exponents
</blockquote></details>

I don't know why we do it honestly, this is old code that I have just made generic!

I asked ChatGPT and it looks like this choice is abritrary!
___
*[`crates/utils/src/math.cairo` line 115 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXXIoS1UzGKRhEclLc:-NoXmfOs4UxXY1e-z2JX:b1eqp9a) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L115)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Should respect rustdoc format and be in the trait definition. copilot chat is really good at creating function docs, I usually let it do the work
</blockquote></details>

do we need to add comments here as well? It is redundant, as someone can just go and see the doc at the trait. 
___
*[`crates/utils/src/math.cairo` line 90 at r7](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXkqz65rIAVDOLrQ66:-NoXmY5VCnww73T-PpUj:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/f5cda99c5538ef861978c54f96224b3bef622159/crates/utils/src/math.cairo#L90)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Can be removed as it doesn't panic
</blockquote></details>

done
___
*[`crates/utils/src/math.cairo` line 94 at r7](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXksKRB27C3aWbehIP:-NoXmYcv-FgeU66S5nId:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/f5cda99c5538ef861978c54f96224b3bef622159/crates/utils/src/math.cairo#L94)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

I don't think it's applicable here, we can remove the section
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-01-19 17:38 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703)* status: 1 of 2 files reviewed, 18 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/math.cairo` line 235 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXZ0kf-oeCB_5mY777:-NoXnNFMEPQtzOSMr4Os:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L235)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

casing
</blockquote></details>

done
___
*[`crates/utils/src/math.cairo` line 245 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXZNC4DCXDk-ZeJQ1j:-NoXn2gk3JFZyklQOKdb:by0h94i) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L245)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

I think this is just a complicated way of checking whether `result > U8_MAX`. You don't actually need the top word, it's just a condition to return a flag.
</blockquote></details>

Hmm, this is how u will do it right? Firstly u have to do a wide_mul, and then figure out if there is an overflow or not.
___
*[`crates/utils/src/math.cairo` line 252 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXZU_TDRtxy1AE1jot:-NoXmxDr-UKVt9eCre81:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L252)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

casing
</blockquote></details>

done
___
*[`crates/utils/src/math.cairo` line 267 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXamkoERG7oPVE8n63:-NoXmwiE65IeRv0kQTsA:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L267)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

casing
</blockquote></details>

done
___
*[`crates/utils/src/math.cairo` line 279 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXalSy4-4EaLhzjt3m:-NoXmw0d7cKaD1zK0fEC:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L279)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

casing
</blockquote></details>

done
___
*[`crates/utils/src/math.cairo` line 285 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXakMi7JXSh8H03Ks8:-NoXmv344HbGsAKbtQvx:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L285)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

casing
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-01-19 18:00 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703)* status: 0 of 2 files reviewed, 18 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/math.cairo` line 121 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXYAbyBTt6Wr5fL9yi:-NoXrH105RYiq88xAdU4:b-tgetzf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L121)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Are you sure this implementation works for exponent=0? Please add a test.
</blockquote></details>

test has been added.

Done
___
*[`crates/utils/src/math.cairo` line 231 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXYVxp8i-Q8uJehYEk:-NoXsPSU9CSPzbwyq7Xu:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L231)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Rustdoc-compliant format (copilot chat helps a lot)
</blockquote></details>

done
___
*[`crates/utils/src/math.cairo` line 293 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXabKiEgyM80lsJJzz:-NoXsL_v-WqGKcDuBXL0:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L293)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Rustdoc compliant function doc - don't forget proper casing (a sentence starts with an uppercase letter)
</blockquote></details>

done
___
*[`crates/utils/src/math.cairo` line 74 at r7](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXkivM9L9j0iidXFuT:-NoXsNNkDa4f7syICQj1:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/f5cda99c5538ef861978c54f96224b3bef622159/crates/utils/src/math.cairo#L74)):*
> ```Cairo
>     /// a wrapping strategy to handle overflow. This means if intermediate or final results
>     /// overflow the type `T`, they will wrap around according to the rules defined for
>     /// the `wrapping_mul` method in Rust's standard library.
> ```

done


<!-- Sent from Reviewable.io -->

2024-01-19 18:00 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703)* status: 0 of 2 files reviewed, 18 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/math.cairo` line 240 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXZ33L5a-gV0_dRibB:-NoXsQmS75Wp7QYXLhO7:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L240)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

if you want to get the top word, why not masking with 0xFF00 instead ? here you're doing a lot of un-necessary operations
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-01-19 18:32 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703)* status: 0 of 2 files reviewed, 18 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/math.cairo` line 99 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXXG1k5UkQeEw_wPno:-NoXzZR-3szumfEMwIhK:b3tr0hj) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L99)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Should respect rustdoc format and be in the trait definition
</blockquote></details>

It is now in only in trait definition


<!-- Sent from Reviewable.io -->

2024-01-19 20:53 UTC, enitrat requested changes
Last touch and LGTM :)

> Reviewed 1 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-:-NoYUva7-1izBAaypjx4:baxk28c)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @bajpai244 and @ClementWalter)

___
*[`crates/utils/src/math.cairo` line 61 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXX852BbVA1fLTsyiS:-NoYOAIuCVuf6cSaydbi:ba0glwy) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L61)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

I don't know why we do it honestly, this is old code that I have just made generic!

I asked ChatGPT and it looks like this choice is abritrary!
</blockquote></details>

This is because for exponent < 10, it's actually cheaper to run the slow version given that the CAIRO CPU architecture doesn't price stuff like a physical chip (indeed, not your comment but good to know!)
___
*[`crates/utils/src/math.cairo` line 115 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXXIoS1UzGKRhEclLc:-NoYOTMm6Zlb7DpXSg6T:ba3awle) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L115)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

do we need to add comments here as well? It is redundant, as someone can just go and see the doc at the trait.
</blockquote></details>

indeed only in the trait
___
*[`crates/utils/src/math.cairo` line 121 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXYAbyBTt6Wr5fL9yi:-NoYOUo08s_MwgtdL-63:b-hxbai1) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L121)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

test has been added.

Done
</blockquote></details>

sorry - I mean `self` (base) = 0. I think it's fine actually since base == 0 => x * 0 = 0 in any case
___
*[`crates/utils/src/math.cairo` line 245 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXZNC4DCXDk-ZeJQ1j:-NoYTXEA2asvYV18y3Qr:b-h2tvdo) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L245)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

Hmm, this is how u will do it right? Firstly u have to do a wide_mul, and then figure out if there is an overflow or not.
</blockquote></details>

you take a u8, you wide mul it by another u8, you get a u16
e.g
0xFF * 0xFF = 0xFE01

Your goal is to get the result of the overflowing operation and a boolean indicating if the result has overflown. 
- The result of the operation is `res & bottom_mask`
- The boolean flag is set to true if `res > 0xFF`, false otherwise

no need to use a top_mask to isolate the top_part 
___
*[`crates/utils/src/math.cairo` line 374 at r11](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoYUFkN3w-7IxExNAZ6:-NoYUFkN3w-7IxExNAZ7:b-rvsyne) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/875d971dcd9930bcb8759357762666ebfeb3dae7/crates/utils/src/math.cairo#L374)):*
> ```Cairo
>     ///
>     /// let result = BoundedInt::<u32>::max().overflowing_mul(BoundedInt::max());
>     /// assert_eq!(result, u32::MAX.wrapping_mul(1));
> ```

These are incorrect - even if copilot helps with the high-order description of the function pretty well, the examples are not necessarily correct

I'm actually not sure we should even include examples - it's heavy and since we're not writing a user-facing library I don't think it's necessary. I would be in favor or removing examples from docs (unless really helpful)



_Code quote:_
```Cairo
    /// # Examples
    /// ```
    /// let result = 1_000_000_000_u256.overflowing_mul(2);
    /// assert_eq!(result, 2_000_000_000);
    ///
    /// let result = BoundedInt::<u32>::max().overflowing_mul(BoundedInt::max());
    /// assert_eq!(result, u32::MAX.wrapping_mul(1));
```


<!-- Sent from Reviewable.io -->

2024-01-20 09:40 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/math.cairo` line 121 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXYAbyBTt6Wr5fL9yi:-NoaC7aX1olk-RTNhWWv:b-1c1ywt) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L121)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

sorry - I mean `self` (base) = 0. I think it's fine actually since base == 0 => x * 0 = 0 in any case
</blockquote></details>

Gotcha, I have added a test for this case as well!

I am thinking of what should be the behaviour of 0^0! I think something for another issue, for now it returns 0, but we would have to look into some maths lib to understand what it should be!

I can create an issue for this.
___
*[`crates/utils/src/math.cairo` line 245 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXZNC4DCXDk-ZeJQ1j:-NoaBStAEIUUCK_D_AwE:b2e9fy7) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L245)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

you take a u8, you wide mul it by another u8, you get a u16
e.g
0xFF * 0xFF = 0xFE01

Your goal is to get the result of the overflowing operation and a boolean indicating if the result has overflown. 
- The result of the operation is `res & bottom_mask`
- The boolean flag is set to true if `res > 0xFF`, false otherwise

no need to use a top_mask to isolate the top_part
</blockquote></details>

Ah, yeah this makes more sense! Refactored accordingly!
___
*[`crates/utils/src/math.cairo` line 374 at r11](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoYUFkN3w-7IxExNAZ6:-NoaBz2m-wpfgjeeKaED:blcbt7g) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/875d971dcd9930bcb8759357762666ebfeb3dae7/crates/utils/src/math.cairo#L374)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

These are incorrect - even if copilot helps with the high-order description of the function pretty well, the examples are not necessarily correct

I'm actually not sure we should even include examples - it's heavy and since we're not writing a user-facing library I don't think it's necessary. I would be in favor or removing examples from docs (unless really helpful)
</blockquote></details>

Ah, I corrected the code in above part but missed it in the assert statement, I am fine with removing them as well!


Removed.


<!-- Sent from Reviewable.io -->

2024-01-20 09:47 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/math.cairo` line 115 at r5](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NoXXIoS1UzGKRhEclLc:-NoaG7FE6UKpoIDMKhKn:b-896fix) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/8cc18749c2cd7181ac906c1ca82e4b11204c6023/crates/utils/src/math.cairo#L115)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

indeed only in the trait
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-22 09:06 UTC, enitrat requested changes
LGTM after this

> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-:-NokPrxj4v44sPGpLr3W:bfv57op)* status: all files reviewed, 2 unresolved discussions (waiting on @bajpai244 and @ClementWalter)

___
*[`crates/utils/src/math.cairo` line 296 at r13](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NokPcpN1Hn1XqvJZpL-:-NokPcpN1Hn1XqvJZpL0:bvt6kty) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/1c2bbddaccf487864dbb26b13aa1fed8eea1e783/crates/utils/src/math.cairo#L296)):*
> ```Cairo
>         let bottom_word = (result & mask).try_into().unwrap();
> 
>         if result > mask {
> ```

let is_overflown = result > mask;
return (bottom_word, is_overflown)
___
*[`crates/utils/src/math.cairo` line 311 at r13](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NokPmLv3E-_LOO1lMOB:-NokPmLv3E-_LOO1lMOC:bnj7hl0) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/1c2bbddaccf487864dbb26b13aa1fed8eea1e783/crates/utils/src/math.cairo#L311)):*
> ```Cairo
>         let bottom_word = (result & mask).try_into().unwrap();
> 
>         if result > mask {
> ```

same as above


<!-- Sent from Reviewable.io -->

2024-01-22 10:12 UTC, bajpai244 reviewed
done

> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-:-Noke-at3W7gDwG1wtv9:bb7f2mf)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/math.cairo` line 296 at r13](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703#-NokPcpN1Hn1XqvJZpL-:-Noke1ERC0_ReGF3awJJ:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/1c2bbddaccf487864dbb26b13aa1fed8eea1e783/crates/utils/src/math.cairo#L296)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

let is_overflown = result > mask;
return (bottom_word, is_overflown)
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-01-22 12:38 UTC, enitrat approved these changes
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ClementWalter)



<!-- Sent from Reviewable.io -->

2024-01-22 12:44 UTC, merged