feat: add ModExp core lib
kkrt-labs/kakarot-ssj pull request #718
Opened 2024-01-29 06:54 UTC by bajpai244

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

Resolves: #711

2024-01-29 16:07 UTC, enitrat requested changes
Awesome work !

> Reviewed 17 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-:-NpKyREe7zS562fjLb0K:bpj8b6c)* status: 17 of 19 files reviewed, 70 unresolved discussions (waiting on @bajpai244 and @ClementWalter)

___
*[`crates/utils/src/checked_math.cairo` line 130 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJc_el91Z-0GjcPvra:-NpJc_el91Z-0GjcPvrb:bgbvet8) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/checked_math.cairo#L130)):*
> ```Cairo
>         /// # Returns
>         /// `Some(self * rhs)` if the multiplication doesn't overflow, and `None` otherwise.
>         fn checked_mul(self: T, rhs: T) -> Option<T>;
> ```

Add to CheckedMath trait
___
*[`crates/utils/src/checked_math.cairo` line 149 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJccmcDzynNhqQyLvX:-NpJccmcDzynNhqQyLvY:bym2cyk) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/checked_math.cairo#L149)):*
> ```Cairo
> mod tests {
>     use integer::BoundedInt;
>     use super::{checked_math::CheckedMath, checked_mul::CheckedMul};
> ```

so that you can access it through CheckedMath only
___
*[`crates/utils/src/helpers.cairo` line 989 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJf33J7OgqOosiXcTf:-NpJf33J7OgqOosiXcTg:bhhv4sm) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/helpers.cairo#L989)):*
> ```Cairo
> > of FromBytes<T> {
>     fn from_be_bytes(self: Span<u8>) -> Option<T> {
>         let byte_size = BitSize::<T>::bits() / 8;
> ```

let's create a ByteSize<T> trait
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 24 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKIvO04M2qrvq7eUor:-NpKIvO04M2qrvq7eUos:b-8kr799) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L24)):*
> ```Cairo
> fn monpro(ref x: MPNat, ref y: MPNat, ref n: MPNat, n_prime: Word, ref out: Felt252Vec<Word>) {
>     let s = out.len() - 2;
>     // Using a range loop as opposed to `out.iter_mut().enumerate().take(s)`
> ```

:thinking: what's this
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 153 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKNgcW93LmyHz4T8Lt:-NpKNgcW93LmyHz4T8Lu:b-gj4dos) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L153)):*
> ```Cairo
>         let mut j = i + s;
>         loop {
>             if c <= 0 {
> ```

I think it's safe to say that `c` will never be below 0 (it's an unsigned integer)



_Suggestion:_
```Cairo
if c == 0 {
```
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 166 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKPkVcD3EKxtm4y9X3:-NpKPkVcD3EKxtm4y9X4:br89s4v) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L166)):*
> ```Cairo
>     };
> 
>     // Only keep the last `s + 1` digits in `out`.
> ```

I think we should create a new Vec, fill it with the content from `out`, and then assign `out = new_out` or something. This way in the next instruction `fill(0)` we can simply expand the length of the `new_out` to fill it with zeroes (and I think there's already a util for that)
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 176 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKNx4d3WWUPLY5pfAH:-NpKNx4d3WWUPLY5pfAI:b-7mrkoe) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L176)):*
> ```Cairo
> 
>         i += 1;
>     };
> ```

I have idea for optimisations of these: a struct
```rust
struct ResizableVec{
  start_idx: felt252,
  end_idx: felt252,
  data: Felt252Dict<T>
}
```

We could remove the first `n` digits by moving the start_idx by `n`
Let's keep it in mind for a round of optimizations: https://github.com/kkrt-labs/kakarot-ssj/issues/720 - not to be addressed here



_Code quote:_
```Cairo
    // Only keep the last `s + 1` digits in `out`.
    let mut i = 0;
    loop {
        if i == s + 1 {
            break;
        };

        out.set(i, out[i + s]);

        i += 1;
    };
```
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 179 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKPUMD7y1nLvnbwiyS:-NpKPUMD7y1nLvnbwiyT:b-st1it3) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L179)):*
> ```Cairo
> 
>     let mut i = s + 1;
>     loop {
> ```

Optimization idea: simply expand the length of `out` to `out.len`
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 184 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKOv5w3sKDoNYI3KEZ:-NpKOv5x3K5qt4T_D7Zi:b20fbnz) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L184)):*
> ```Cairo
>         };
> 
>         // todo(harsh): can this set an index which doesn't exist?
> ```

I think `set` fails if `index > len`
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 237 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKQXkPEFwnkephH0Jd:-NpKQXkPEFwnkephH0Je:bbrqixl) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L237)):*
> ```Cairo
> ) -> MPNat {
>     let mut digits = Felt252VecImpl::new();
>     digits.resize(scratch_space.len(), 0);
> ```

! I missed this in the previous review: can you modify the function signature of `resize` to not take a value `T` because in any case it will be filled with zeroes?
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 248 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKQofPBYcl3mHwsPu3:-NpKQofPBYcl3mHwsPu4:b8y4e5r) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L248)):*
> ```Cairo
> 
>         i += 1;
>     };
> ```

empty operation



_Code quote:_
```Cairo
    loop {
        if i == exp.len() {
            break;
        }

        i += 1;
    };
```
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 257 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKR4i-BVdpc9dWFJ90:-NpKR4i-BVdpc9dWFJ91:b-4d7yaa) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L257)):*
> ```Cairo
> 
>         let b = *exp[i];
>         let mut mask: u8 = 1_u8.wrapping_shl(7);
> ```

1 << 7 = 128

when you encounter any bit operation, you should ask yourself whether it's possible to do something more optimized when applied to the architecture and compiler you're working with. I'm pretty sure 1 << 7 is compiled to 128 in rust, but not in Cairo (since in any case we're using a custom function.

Overall, any operation that involves two constants can often be directly a constant.
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 260 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKRBqh9uxVL6Jw7rw9:-NpKRBqh9uxVL6Jw7rwA:undefined) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L260)):*
> ```Cairo
> 
>         loop {
>             if mask <= 0 {
> ```





_Suggestion:_
```Cairo
mask == 0
```
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 267 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKRklPD993uhNIhGp_:-NpKRklPD993uhNIhGpa:bo1khb [...]

2024-01-30 09:57 UTC, bajpai244 reviewed
Thanks :)

> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-:-NpOPb428VfpmsxNFV8S:bvtk9y9)* status: 16 of 19 files reviewed, 70 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/helpers.cairo` line 989 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJf33J7OgqOosiXcTf:-NpOepYQ15E5pW7btdG6:bb6un1j) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/helpers.cairo#L989)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

let's create a ByteSize<T> trait
</blockquote></details>

Done
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 24 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKIvO04M2qrvq7eUor:-NpOh_zw8i3o1mW-If6u:bo6f0tv) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L24)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

:thinking: what's this
</blockquote></details>

This was borrowed from the rust codebase, doesn't apply to use removed
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 153 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKNgcW93LmyHz4T8Lt:-NpOhtEr2OIpiWFm1Nyl:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L153)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

I think it's safe to say that `c` will never be below 0 (it's an unsigned integer)
</blockquote></details>

done
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 166 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKPkVcD3EKxtm4y9X3:-NpOkoa99O-p7-Bcidfu:bln6zo5) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L166)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

I think we should create a new Vec, fill it with the content from `out`, and then assign `out = new_out` or something. This way in the next instruction `fill(0)` we can simply expand the length of the `new_out` to fill it with zeroes (and I think there's already a util for that)
</blockquote></details>

Makes sense, done, I also realized we could just do 

` // Only keep the last `s + 1` digits in `out`.
   
let mut new_vec: Felt252Vec<u64> = out.clone_slice(s, s + 1);` to create the new_vec
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 176 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKNx4d3WWUPLY5pfAH:-NpOmx-eAdrb6xaWCL27:b-pz2tnp) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L176)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

I have idea for optimisations of these: a struct
```rust
struct ResizableVec{
  start_idx: felt252,
  end_idx: felt252,
  data: Felt252Dict<T>
}
```

We could remove the first `n` digits by moving the start_idx by `n`
Let's keep it in mind for a round of optimizations: https://github.com/kkrt-labs/kakarot-ssj/issues/720 - not to be addressed here
</blockquote></details>

This looks interesting, I have for now performed the optimisation u suggested in the previous comment, right now in this PR i don't think we should change the code too much, as we will follow with another PR for integration of the pre-compile, and we don't know if the changes we make here might break something there.

So, I guess great to have it as an issue, and then once we have everything merged, we can do the refactor!


<!-- Sent from Reviewable.io -->

2024-01-30 10:44 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 15 of 19 files reviewed, 70 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 179 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKPUMD7y1nLvnbwiyS:-NpOng_99r5BKo_lSWHP:bnd2a8c) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L179)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Optimization idea: simply expand the length of `out` to `out.len`
</blockquote></details>

This part of code is now removed, we are using `expand` util, which does the same!
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 184 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKOv5w3sKDoNYI3KEZ:-NpOnm3--CGQb9EIXdBp:biolkd3) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L184)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

I think `set` fails if `index > len`
</blockquote></details>

the code no longer exits, we use `clone_slice`
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 237 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKQXkPEFwnkephH0Jd:-NpOnqu9AWMtDWLe1LwS:bcviwpd) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L237)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

! I missed this in the previous review: can you modify the function signature of `resize` to not take a value `T` because in any case it will be filled with zeroes?
</blockquote></details>

I think the right utils here should be `expand`, which fills it by zero, 
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 248 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKQofPBYcl3mHwsPu3:-NpOwjti8w5T6o-TzWwA:b-dhdbl3) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L248)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

empty operation
</blockquote></details>

lo! removed
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 257 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKR4i-BVdpc9dWFJ90:-NpOxBdd3dQ2xmn7adP-:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L257)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

1 << 7 = 128

when you encounter any bit operation, you should ask yourself whether it's possible to do something more optimized when applied to the architecture and compiler you're working with. I'm pretty sure 1 << 7 is compiled to 128 in rust, but not in Cairo (since in any case we're using a custom function.

Overall, any operation that involves two constants can often be directly a constant.
</blockquote></details>

done
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 260 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKRBqh9uxVL6Jw7rw9:-NpOxE_W3nzfIIHigbBe:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L260)):*
> ```Cairo
> 
>         loop {
>             if mask <= 0 {
> ```

done
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 267 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKRklPD993uhNIhGp_:-NpOxlNfCbAY7mwECw4h:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L267)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

can you add a //TODO: optimize on this?

There could be a better way then deep cloning result, we will look into it later
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-01-30 12:49 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 15 of 19 files reviewed, 70 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 277 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKS-T49AKwBNeNuviR:-NpOy5QW8eXeIz2_P81R:b-5xz7at) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L277)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

shr
</blockquote></details>

we need wrapping_shr, I remember there are tests which require this behaiour
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 300 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJvto8BwC8k1EleRWz:-NpOycOk5-wRO-CSdxRd:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L300)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

stop condition outside of inner loop
</blockquote></details>

done
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 403 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJlid65UZkiz3IBxRI:-NpPPVjv4iJXKd2D2noI:b-7ql1td) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L403)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

proper docstring
</blockquote></details>

fixed
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 419 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJl4CzC4uN6eF0Oue3:-NpPPX2n50hbnXFYd0rw:b-uclb8f) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L419)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

What's "carry the 1" semantics ? It's not explicit.
</blockquote></details>

The comments are borrowed from Aurora, as it is, I don't know the carry the 1 semantics mean as well.
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 432 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJlQiYAX83EblW4sQJ:-NpPPiqBDdYdbgJV9bem:b45kfs9) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L432)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

What's "borrow from your neighbour" semantics?
</blockquote></details>

addressed above, the comments are borrowed as it is from Aurora


<!-- Sent from Reviewable.io -->

2024-01-30 13:07 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 15 of 19 files reviewed, 70 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 446 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJmhui98sx_sYO_B0N:-NpPQmCU-xYOhFam5Dju:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L446)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

docstring
</blockquote></details>

done
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 448 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJnCF52zVb2utUPFaF:-NpPQpH4BOBEUYp6osJc:b-8zxnb8) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L448)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

What is this BitOr for? Why not just adding low + high instead of doing bit operations?
</blockquote></details>

Yeah, u are correct after shl, we can just add them! 

Done
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 468 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJpO45A4Zj3kZJqf4T:-NpPRHALAylJm8f2L7So:bb6un1j) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L468)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

j is incremented by one in each iteration
</blockquote></details>

Done
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 485 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJpw_B1WEAYGx4m7EI:-NpPSHT11X_-_ijKAbyI:b-gften6) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L485)):*
> ```Cairo
>                 Result::Ok(res) => { (res, false) },
>                 Result::Err(res) => { (res, true) }
>             };
> ```

Realized there is no reason to return the tuple! We can just add BASE to new_c inside the arm, done!

Done
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 489 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJq9W18H-qbiGhK-LL:-NpPT-1nAm-Kjt_3B4n4:bb6un1j) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L489)):*
> ```Cairo
>             if overflow {
>                 new_c += BASE;
>             }
> ```

Done
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 493 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJq2CEC4jvVEJUSaCM:-NpPSydF4ngan-Mvm6oz:bb6un1j) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L493)):*
> ```Cairo
>                 Result::Ok(res) => { (res, false) },
>                 Result::Err(res) => { (res, true) }
>             };
> ```

Done
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 496 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJqB0P66qK5wtv_7uj:-NpPT2527dmzk947KIQp:bb6un1j) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L496)):*
> ```Cairo
>             if overflow {
>                 new_c += BASE;
>             }
> ```

Done
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 511 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJtOXpDR8lTn-pHBxb:-NpPTJHd3h0aa7rT3MUe:b-xw0zx9) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L511)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

proper docstring: what's `<<=` ?
</blockquote></details>

Comments are taken as they are from Aurora, from what I understand this is a = a << shift


Which is a valid operation in Rust
![image.png](https://files.reviewableusercontent.io/images/reviewable/41180869/a3UHFHG1zJ-AV0Gfrzm3CvhL/image.png)


<!-- Sent from Reviewable.io -->

2024-01-30 13:10 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 15 of 19 files reviewed, 70 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 522 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJupTS6yyZ1fNB7Gg1:-NpPTwT4-sfVgQ8-tOgS:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L522)):*
> ```Cairo
>         }
> 
>         let a_digit = a[i];
> ```

done
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 524 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJuqw6BonN3c6alBUn:-NpPTx8M2zggeeYqvFvO:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L524)):*
> ```Cairo
>         let a_digit = a[i];
>         let carry = a_digit.wrapping_shr(carry_shift.into());
>         let a_digit = a_digit.wrapping_shl(shift.into()) | c;
> ```

done
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 535 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJtZI9C-8ypmLqNEf8:-NpPTy0z1cioa2pkGLQ6:b-c7tzen) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L535)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

same
</blockquote></details>

have replied above in the comments
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 548 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJugUq79RIvVr52pHY:-NpPU34m52uu5m23hKP2:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L548)):*
> ```Cairo
>         let j = i - 1;
> 
>         let a_digit = a[j];
> ```

done
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 550 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJui288gesk-XOyM4L:-NpPU40f3gfxqcUn-x9Z:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L550)):*
> ```Cairo
>         let a_digit = a[j];
>         let borrow = a_digit.wrapping_shl(borrow_shift.into());
>         let a_digit = a_digit.wrapping_shr(shift.into()) | b;
> ```

done


<!-- Sent from Reviewable.io -->

2024-01-30 14:11 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 15 of 19 files reviewed, 70 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 118 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKdX84DxghbfNLsYen:-NpPeq5d-XqP18YYbbnZ:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L118)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

small nit: but since the field might be private in the future and good practice overall
</blockquote></details>

done
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 134 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKe2EE1aBSRTsDtw6f:-NpPgmTKEZ0dTFj2x70H:b6ildmb) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L134)):*
> ```Cairo
>             // The divisor is only 1 digit, so the long-division
>             // algorithm is easy.
>             let k = self.digits.len - 1;
> ```

I realized there was an error in this loop, fixed
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 135 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKe3bY31WgQmx4I3Ol:-NpPgpI20Y77AlHt6Hr4:b6apy1b) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L135)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

rename `i` to `j`
</blockquote></details>

I no longer need j + we shouldn't use self.digits.len() inside the loop, as transformation inside the loop can change the digits len.
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 141 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKeWiM4kxM2OYHGg_N:-NpPh-l57gP7JBEbX0sl:b-hfpv0l) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L141)):*
> ```Cairo
>                 };
> 
>                 let j = i - 1;
> ```

removed
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 146 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKedVIApue1r2HYXWT:-NpPhHrI8Z7VlUtiHqw8:b-10f0nr) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L146)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

and here you need to decrement `j` (previously `i`)
</blockquote></details>

code has been refactored, and j doesn't exist.


<!-- Sent from Reviewable.io -->

2024-01-30 14:17 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 14 of 19 files reviewed, 70 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 169 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKf44V6IF-Huv0LJL9:-NpPhY_t1upTd_u6OuvM:b-hfpv0l) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L169)):*
> ```Cairo
>             // Normalize other
>             let mut normalized = other.digits.duplicate();
>             let _ = in_place_shl(ref normalized, shift);
> ```

removed
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 193 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKgiGZ80rl1eYFRgKG:-NpPhruu5lCsBOVHPAEF:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L193)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

self.digits.len

(all occurences)
</blockquote></details>

done
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 214 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKh4p164qfLQHpcaGy:-NpPiJVn3eSjgRvYN6DS:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L214)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

add: //TODO: optimize with https://github.com/kkrt-labs/kakarot-ssj/issues/720

we don't need a deep clone, we could simply shift the index of the beginning to fit our needs with a custom SliceVec type that has no write functions.
</blockquote></details>

done
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 217 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKhTL39_aR7LcbOvcp:-NpPijCKCPFrJXckntWn:bpkdnx9) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L217)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

I don't understand what this is for. I think it's not doing anything useful
</blockquote></details>

It does right? a is in place changed by the function before it, and the result is then applied to self.digits
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 222 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKhcj56deCQXYkNc-f:-NpPirKy4aTES-TDirH_:b82f4ag) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L222)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

same
</blockquote></details>

replied on the comment above


<!-- Sent from Reviewable.io -->

2024-01-30 14:28 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 14 of 19 files reviewed, 70 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 304 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKnVMv2JL6bGyA2Dr6:-NpPix45E8RJxwSMI9co:b-beyfaq) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L304)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

add a //TODO: optimize

Instead of duplicating all digits of `a` and then mutating them sequentially, we can just do a function that creates a new empty vec, takes a digit of a, subs the digit of b, and returns the populated vec at the end. Divide by 2 the memory used.
</blockquote></details>

Added the TODO, I would all optimizations after merging the next PR, just to be super sure we aren't break anything.
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 344 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKqSFw5L7LHGxWT0PC:-NpPl1px6KGdwsmdZbfJ:bu1e5kh) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L344)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

useless loop
</blockquote></details>

lol! Not sure how I ended up having this, removed!


<!-- Sent from Reviewable.io -->

2024-01-30 14:30 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 14 of 19 files reviewed, 70 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 352 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKq_L194JkVIz2zwcY:-NpPlS_ECH-_9_ODbI2h:bgbh54w) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L352)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

not sure we want this assert in prod
</blockquote></details>

removed, u are right, it was more of something used in debug mode.
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 356 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKrIBH7ImnsW8oscz8:-NpPlXiy4VX-Vp9LMrpp:b-64wdhh) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L356)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

free optimization
</blockquote></details>

I think push is better, would have to add one more unwrap because of this, which doesn't make sense here.


<!-- Sent from Reviewable.io -->

2024-01-30 15:31 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 14 of 19 files reviewed, 70 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 367 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKrh3cEGtcyh5EkVBK:-NpPySt29_l5eoJAmJ9a:bb6un1j) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L367)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

modify with ByteSize trait and use u64 (see comment below)
</blockquote></details>

Done
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 367 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKrwb60yVYxLypCcqy:-NpPyTN21FW96SnYck7f:b-37lehh) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L367)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

usize in Cairo is u32. In regular computers it's either u32 or u64, thus for us we can pick the biggest size for optimization
</blockquote></details>

I would prefer to keep it a usize, we would have to otherwise do a try_into.unwrap in places where the argument is supposed to be a u32, and I would prefer to avoid it as I don't see us gaining much with it.

![image.png](https://files.reviewableusercontent.io/images/reviewable/41180869/hLVYfsbV_mE8O1vBbcIm76DA/image.png)
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 371 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKsfGlB8F3Bgrbj9Oz:-NpPz6vs8itpzjHNp4CN:b-896fja) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L371)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

this is `from_le_bytes`
</blockquote></details>

Done!
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 418 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKtQhPEAy0d2MXjQcM:-NpPzOvZ84dR7STLnd5Z:bxnlcow) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L418)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

I previously mentioned refactoring resize to not take a value: I realize that it's actually just `extend` - then we can completely remove resize
</blockquote></details>

There is a subtle difference between resize and expand!
 
Expand is for when u want to increase the size of vec, while resize can resize to any size, doesn't matter whether it is greater than or less, this is why we are keeping it, I would have to dig, but I guess not all resize are expands! { I remember getting an error in some tests, and this is why I created this util. }


<!-- Sent from Reviewable.io -->

2024-01-30 15:40 UTC, enitrat requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 15 of 19 files reviewed, 36 unresolved discussions (waiting on @bajpai244 and @ClementWalter)

___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 237 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKQXkPEFwnkephH0Jd:-NpPR_EQAjiHgEM_uuiM:b-6z4nmx) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L237)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

I think the right utils here should be `expand`, which fills it by zero,
</blockquote></details>

yeah, use expand (but either remove resize completely or revert back it's body to actually resize by using the value T provided in param).
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 277 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKS-T49AKwBNeNuviR:-NpPRnBh70DN-t5Ydfga:bbe8k0j) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L277)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

we need wrapping_shr, I remember there are tests which require this behaiour
</blockquote></details>

what happens when you shift right 0? :moon: 
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 419 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJl4CzC4uN6eF0Oue3:-NpPzvpvBfZS3Z7_V6fI:b-n99fdj) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L419)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

The comments are borrowed from Aurora, as it is, I don't know the carry the 1 semantics mean as well.
</blockquote></details>

then we shouldn't have function documetnation we can't understand ourselves :-)
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 432 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJlQiYAX83EblW4sQJ:-NpPzzpY1yPEV1eZh0_L:b-tm5d4m) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L432)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

addressed above, the comments are borrowed as it is from Aurora
</blockquote></details>

We shouldn't keep what we can't understand: try to come up with a description of what the function performs. (chatgpt can help on this!)
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 511 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJtOXpDR8lTn-pHBxb:-NpQ-L7B0OWtMufiA_zc:b-it8f7) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L511)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

Comments are taken as they are from Aurora, from what I understand this is a = a << shift


Which is a valid operation in Rust
![image.png](https://files.reviewableusercontent.io/images/reviewable/41180869/a3UHFHG1zJ-AV0Gfrzm3CvhL/image.png)
</blockquote></details>

Can you modify the comment? In our case since a is a Vec of word perhaps something that describes internally what happens would be good
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 356 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKrIBH7ImnsW8oscz8:-NpQ0CxS15dNVDFbTRRm:behpdfg) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L356)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

I think push is better, would have to add one more unwrap because of this, which doesn't make sense here.
</blockquote></details>

yeah ok not super opiniated on this, but doing `push(0)` is doing one extra write for nothing since it's just increasing the len by one
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 418 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKtQhPEAy0d2MXjQcM:-NpQ0Qtq8zBa9bAquLAX:b-e2hmkq) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L418)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

There is a subtle difference between resize and expand!
 
Expand is for when u want to increase the size of vec, while resize can resize to any size, doesn't matter whether it is greater than or less, this is why we are keeping it, I would have to dig, but I guess not all resize are expands! { I remember getting an error in some tests, and this is why I created this util. }
</blockquote></details>

Ah, yeah you're right. In which case: before doing `resize`, since we're not erasing the actual content written inside the dict, we must make sure that there is no call to `expand` performed after! Otherwise we would be increasing the length of the vector, thinking indexes are empty, when they're not. Perhaps we could work on a better type system to disable extending a vec that has been resized. Anyway: in our case, I think it doesn't happen.


<!-- Sent from Reviewable.io -->

2024-01-30 16:06 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 15 of 19 files reviewed, 36 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 418 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKtQhPEAy0d2MXjQcM:-NpQ6KIr8YNC-kllqyBW:b-tup7s5) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L418)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Ah, yeah you're right. In which case: before doing `resize`, since we're not erasing the actual content written inside the dict, we must make sure that there is no call to `expand` performed after! Otherwise we would be increasing the length of the vector, thinking indexes are empty, when they're not. Perhaps we could work on a better type system to disable extending a vec that has been resized. Anyway: in our case, I think it doesn't happen.
</blockquote></details>

Yeah, I guess for now it doesn't happen, but good point to consider!
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 428 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKtr254IMEvQqcYRtZ:-NpQ6PMm0OxsJNYYJBDJ:b-lqc4jj) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L428)):*
> ```Cairo
>             let num_digits = modulus.digits.len() - trailing_zeros;
>             let mut digits = Felt252VecImpl::new();
>             digits.resize(num_digits, 0);
> ```

addressed that resize and extend are different in behaviours.

I guess we can make a seperate issue to check which resizes are safe to change to `extend.`


<!-- Sent from Reviewable.io -->

2024-01-30 16:08 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 15 of 19 files reviewed, 36 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 424 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKtkEs9JQua5vPc4dT:-NpQ7AgB3n94FSsxcvYx:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L424)):*
> ```Cairo
>         };
> 
>         let power_of_two_mask = power_of_two.digits[power_of_two.digits.len - 1] - 1;
> ```

done
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 480 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKvEwC7y8zU5cP9aKr:-NpQ7CCKAk7X7juQlBus:bj32rtg) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L480)):*
> ```Cairo
>         let s = power_of_two.digits.len();
>         let mut scratch: Felt252Vec<Word> = Felt252VecImpl::new();
>         scratch.resize(s, 0);
> ```

addressed in above comments, we should firstly merge this, and after the next PR is merged, we can re-access which resize are safe, and which aren't. 


<!-- Sent from Reviewable.io -->

2024-01-30 16:12 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 15 of 19 files reviewed, 36 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 456 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKuEKQ12DYW_aVuAbM:-NpQ7b1TA-VH2yfyFH9n:bdyirr4) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L456)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

I think we could have a copy_from_slice that would avoid duplicating the clone => insert operation and just insert in place in `tmp`, kind of like `copy_from_vec` but with a start index and length
</blockquote></details>

I adding a TODO comment to explore this possibility, I would firstly like to get a complete merge. and then explore optimizations. as the codebase is huge, and we should approach these one by one, and make sure nothing breaks { i.e all tests pass as they are supposed to }
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 544 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKwXa6CPFqTBwuWiJC:-NpQ7PBz2T6b9-Z4IRZr:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L544)):*
> ```Cairo
>         // `r = 2^(WORD_BITS*modulus.digits.len())`.
>         let n_prime = WORD_MAX - mod_inv(modulus.digits[0]) + 1;
>         let s = modulus.digits.len;
> ```

done


<!-- Sent from Reviewable.io -->

2024-01-30 16:49 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 15 of 19 files reviewed, 36 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 237 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKQXkPEFwnkephH0Jd:-NpQBihi6PKZ-cAMRgIT:b8qj4xe) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L237)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

yeah, use expand (but either remove resize completely or revert back it's body to actually resize by using the value T provided in param).
</blockquote></details>

What do u mean by actually resizing? It does resizes the vec
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 277 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKS-T49AKwBNeNuviR:-NpQCbN9E4lNWwFGfBJL:b-77vern) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L277)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

what happens when you shift right 0? :moon:
</blockquote></details>

Hmm, it will return 0 right?

![image.png](https://files.reviewableusercontent.io/images/reviewable/41180869/lJElcZs0_A7ldcoScvRekHWI/image.png)
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 498 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJqa6M0ajtJn-uN149:-NpQFER19Tz1HtlpH4Xi:b-dslnnk) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L498)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

regular shr.
Now that I think of it: wrapping_shr doesn't make sense, if you shift right by more than T bits, then the result is just 0.
There is a mistake in the implementation of `fn shr`, please fix it as well to this:

```rust
    fn shr(self: T, shift: T) -> T {
        // early return to save gas if shift > nb_bits of T
        if shift > shift.size_of() - One::one() {
            return Zero::zero()
        }
        let two = One::one() + One::one();
        self / two.pow(shift)
    }
```

and remove `wrapping_shr` from `WrappingBitshift` trait (it doesn't make sense to have it at all)
</blockquote></details>

Actually, I realized that wrapping_shr and wrapping_shl are what shr and shl should be! 

i.e even wrapping_shl doesn't make sense, because we anyway should discard any overflowing digits.

refactoring.

![image.png](https://files.reviewableusercontent.io/images/reviewable/41180869/_GCyM1eDTLebLpz976LlZxNO/image.png)
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 356 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKrIBH7ImnsW8oscz8:-NpQG31y2rt8S4-n8Vqd:b72x6w1) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L356)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

yeah ok not super opiniated on this, but doing `push(0)` is doing one extra write for nothing since it's just increasing the len by one
</blockquote></details>

Okay, makes sense then, done.


<!-- Sent from Reviewable.io -->

2024-01-30 17:06 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 15 of 19 files reviewed, 36 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 328 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJwS-W4eUwBkHS-YEj:-NpQIjxjBsYBrrIoXYk0:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L328)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

shouldnt wrap, and can't panic since `i < WORD_BITS` anyway
</blockquote></details>

done
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 448 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJn0TLDBmYSuWVlY4N:-NpQJ5JXAeH56K5ypd5R:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L448)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

regular `shl`
</blockquote></details>

done
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 505 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJrdsPBuUB1V1NDOrZ:-NpQJXZp5YmfzbOt1tUq:b6m0vm1) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L505)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

change all `wrapping_shr` to `shr`
</blockquote></details>

did it everywhere apart from `in_place_shr`, where shift <= 64, and hence in case when shift = 64, the code can panic.


<!-- Sent from Reviewable.io -->

2024-01-30 17:10 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 15 of 19 files reviewed, 36 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 505 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJrdsPBuUB1V1NDOrZ:-NpQLKK14auM_8TK15NA:b-u1utyy) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L505)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

did it everywhere apart from `in_place_shr`, where shift <= 64, and hence in case when shift = 64, the code can panic.
</blockquote></details>

+ `in_place_shl` also uses wrapping_shr, as the shift value can overflow.
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 523 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJt5RT6mIM7SLsbOKS:-NpQKwAdDGJY_2OWvKaa:b-6npscq) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L523)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

the source aurora code uses `overflowing_shr` (different from wrapping !), however they only use the index 0 of the tuple which is only the result of the shr operation, thus we can use regular shr
</blockquote></details>

But, that means we need wrapping! Because in our case shr will panic if the shift is more than BitSize of the type!

I will keep it here, as I remember there was a test which failed exactly because of this.


<!-- Sent from Reviewable.io -->

2024-01-30 17:11 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 15 of 19 files reviewed, 36 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 615 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJvcVZ91Ourb_E9N2w:-NpQLYSd89eA6eRG08OJ:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L615)):*
> ```Cairo
>             - ((x_digit.into()) * (y.into()));
> 
>         let new_offset_carry = (offset_sum.wrapping_shr(WORD_BITS.into())).as_u64();
> ```

done


<!-- Sent from Reviewable.io -->

2024-01-30 17:12 UTC, enitrat requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 15 of 19 files reviewed, 26 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 237 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKQXkPEFwnkephH0Jd:-NpQJbUz3GOnSv93vyV5:b-6w9gjy) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L237)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

What do u mean by actually resizing? It does resizes the vec
</blockquote></details>

```rust
    fn resize(ref self: Felt252Vec<T>, new_len: usize, value: T) {
        self.len = new_len;
    }
```

value is not used: resize is the same as expand. Since we never resize with anything else than 0, we should delete it. If we keep it, then its body should be changed.
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 277 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKS-T49AKwBNeNuviR:-NpQJqc_EyWj8Q5WgFSM:b-ouvujp) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L277)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

Hmm, it will return 0 right?

![image.png](https://files.reviewableusercontent.io/images/reviewable/41180869/lJElcZs0_A7ldcoScvRekHWI/image.png)
</blockquote></details>

yeah, thus, wrapping_shr doesn't make any sense, because you cannot go lower than 0. Thus it can be completely deleted from the codebase (we can do this in a later PR), but for the moment, we can replace all `wrapping_shr` by `shr` in this code (since they're strictly equivalent).
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 498 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJqa6M0ajtJn-uN149:-NpQK9Ca5i_GaVya7hrM:b-ao7uvt) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L498)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

@enitrat I was wrong in the previous comment! It does make sense to have panic in case of shr, if the shift is more than 
 size of the variable in bits!

This behaviour is observed in Rust, and we should try to be as close to it as possible.

![image.png](https://files.reviewableusercontent.io/images/reviewable/41180869/Y7zgkLN61yH5EIwSadiHB293/image.png)

I can safely right shift till 7, but not beyond that, as the shift will be more than the bitsize of u8. So, I guess we do need both wrapping shifts and regular ones, as rust also has them!

![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/41180869/7U9j5PkFmZeIcAMG5tKNzvn8/image.png)
</blockquote></details>

We can safely delete all `wrapping_shr` - regarding `wrapping_shl` there is one single occurence in your code where it's useful (where in the rust code they're doing `overflow_shl` / `overflowing_shl`, cant remember correctly), all the rest should be simple `shl`as any unexpected shift higher than that should panic as it's not intended to.
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 367 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKrwb60yVYxLypCcqy:-NpQKZGNBBfLsDRGYcGK:b-qggszr) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L367)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

I would prefer to keep it a usize, we would have to otherwise do a try_into.unwrap in places where the argument is supposed to be a u32, and I would prefer to avoid it as I don't see us gaining much with it.

![image.png](https://files.reviewableusercontent.io/images/reviewable/41180869/hLVYfsbV_mE8O1vBbcIm76DA/image.png)
</blockquote></details>

fine for me! If it's kept as a usize then 
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 428 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKtr254IMEvQqcYRtZ:-NpQL8C03PGWIRTamHBP:b-pty0nf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L428)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

addressed that resize and extend are different in behaviours.

I guess we can make a seperate issue to check which resizes are safe to change to `extend.`
</blockquote></details>

see answer above: for now as they're coded they're strictly equivalent
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 702 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKxaDu1CZoZ7obY-lo:-NpQLZelAlf0Ru_TXPl1:b-z4xsyr) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L702)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

Isn't this more expensive?

For each iteration in the loop u are creating a new stripped_span which denotes `v`?
</blockquote></details>

not really, you're just assigning to the label `v` the current starting idx of the span, this is (or should) be a free operation since you're not actually writing anything in memory.


<!-- Sent from Reviewable.io -->

2024-01-30 17:21 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 15 of 19 files reviewed, 26 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 419 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJl4CzC4uN6eF0Oue3:-NpQN_dv9t9iE_pYk8N7:bjc0j38) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L419)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

then we shouldn't have function documetnation we can't understand ourselves :-)
</blockquote></details>

comment is fixed
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 432 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJlQiYAX83EblW4sQJ:-NpQO-9GEAyazMFnZw0y:b84ghf1) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L432)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

We shouldn't keep what we can't understand: try to come up with a description of what the function performs. (chatgpt can help on this!)
</blockquote></details>

simplified the comment


<!-- Sent from Reviewable.io -->

2024-01-30 17:22 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 15 of 19 files reviewed, 26 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 498 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJqa6M0ajtJn-uN149:-NpQO7aY7i4CFDa9jOQF:bhwwmhr) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L498)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

We can safely delete all `wrapping_shr` - regarding `wrapping_shl` there is one single occurence in your code where it's useful (where in the rust code they're doing `overflow_shl` / `overflowing_shl`, cant remember correctly), all the rest should be simple `shl`as any unexpected shift higher than that should panic as it's not intended to.
</blockquote></details>

I have deleted it everywhere apart from two places where it made sense and was required as seen in the rust codebase.


<!-- Sent from Reviewable.io -->

2024-01-30 17:38 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 13 of 19 files reviewed, 26 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 237 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKQXkPEFwnkephH0Jd:-NpQPgw9EhTFZ5zQNUsM:bnp8x1e) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L237)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

```rust
    fn resize(ref self: Felt252Vec<T>, new_len: usize, value: T) {
        self.len = new_len;
    }
```

value is not used: resize is the same as expand. Since we never resize with anything else than 0, we should delete it. If we keep it, then its body should be changed.
</blockquote></details>

Ahh, makes sense what u mean here!

Done
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 277 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKS-T49AKwBNeNuviR:-NpQRRs90FRAZd9d4XO6:b4iar5v) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L277)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

yeah, thus, wrapping_shr doesn't make any sense, because you cannot go lower than 0. Thus it can be completely deleted from the codebase (we can do this in a later PR), but for the moment, we can replace all `wrapping_shr` by `shr` in this code (since they're strictly equivalent).
</blockquote></details>

They aren't strictly equivalent.

shr: You panic if the shift is more than the bit size of the type { can be observed in rust, and i have added a comment explaining the same }
wrapping_shr: the shift can be greater than the bit size of the type  

I have replaced warpping_shr at shr wherever there is no possibility on panic.
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 511 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJtOXpDR8lTn-pHBxb:-NpQORq5Dc3VdhrhB_B-:bonn4ca) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L511)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Can you modify the comment? In our case since a is a Vec of word perhaps something that describes internally what happens would be good
</blockquote></details>

I think the comment is accurate, the data type is Vec, but the comment explains what it does to type as an Arbitraty Multiprecision Integer!


<!-- Sent from Reviewable.io -->

2024-01-30 17:38 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 13 of 19 files reviewed, 26 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 428 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKtr254IMEvQqcYRtZ:-NpQRnBr4VBaExKFclzu:bmslpvy) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L428)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

see answer above: for now as they're coded they're strictly equivalent
</blockquote></details>

done

All resizes have been made to extend apart from those, where the behaviour of resize is expected.


<!-- Sent from Reviewable.io -->

2024-01-30 17:46 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 13 of 19 files reviewed, 26 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 702 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKxaDu1CZoZ7obY-lo:-NpQTgYU91L4wkI1mr4f:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L702)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

not really, you're just assigning to the label `v` the current starting idx of the span, this is (or should) be a free operation since you're not actually writing anything in memory.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-01-30 17:50 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 13 of 19 files reviewed, 26 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 330 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJwtSUCC0gDio-sp72:-NpQUUZ7BTGIZEIpN2ST:b71exp4) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L330)):*
> ```Cairo
>         let mask: u64 = 1_u64.wrapping_shl(i.into()) - 1;
>         let xy = x.wrapping_mul(y) & mask;
>         let q = 1_u64.wrapping_shl((i - 1).into());
> ```

can u elaborate on this? Where does mask's involvement comes here?


<!-- Sent from Reviewable.io -->

2024-01-30 18:05 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 13 of 19 files reviewed, 26 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 60 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKTkY69ITZwvoyH4Vl:-NpQW56iAv_KH6KwerqY:bhfggra) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L60)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

I don't think you need a Dict for this. 

If I understand well, you're only slicing bytes from 0 to r to get the remainder, and then pack it in a u64 word, and set it as a digit in index i.

in the r!=0 case:
you take the slice [0, r], put it in the buffer between [WORD_BYTES - r, WORD_BYTES]
You then convert the buffer to a little_endian span<u8> and then call `from_be_bytes` on this byte slice that was padded with zeroes in the front.
e.g: let's say r = 4 and bytes = [1,2,3,4,5,6,7,8,9,10]
then: buf = [0, 0, 0, 0, 1, 2, 3, 4] and you transform it into a span (so you waste memory space for nothing)
Then you pack all of these into a u64 word that will be 0x1020304

If I'm not mistaken you could directly do: 
`let word = bytes.slice(0,r).from_be_bytes().unwrap()`
</blockquote></details>

So, the initial zeroes here have value! As the representation is little endian! So all early zeroes are  not ignorable.
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 85 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKXtXH2XUkKwQd4DZf:-NpQWgDcBJud0DN1aBoo:b-k46zz9) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L85)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Same here: the buffer is not used in reality.
</blockquote></details>

So, buffer can hold some value here before entering this condition if the r!=0 case is true! So, I won't remove it, as it can hold some value previously which can lie beyond len next_j 


<!-- Sent from Reviewable.io -->

2024-01-30 18:16 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 13 of 19 files reviewed, 26 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 184 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKfcE3ClTx6XNDHhIq:-NpQZqeB4U8AO0HrKN4O:b-gm8qnk) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L184)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

unused: j is used instead

+ I think `j` starts at `m-1` and has an iteration if `j == 0`. so if `m=4`, you execute the body of the loop for 
`j = [3,2,1,0]`. Thus the break condition should be at the end of the body?

edit: ok, I understood why you did it this way - because if we set `j` to start at `m-1` and stop when `j==0` then we're missing one iteration. Thus, I agree to keep `i` and to keep the stop condition at the beginning of the loop for clarity. 

However, I think the first value of `j` is `m-1` thus the first value of `i` should be `m`
</blockquote></details>

Nope! the value of j is m, if we look at the range correctly, it has ..=, which means it is inclusive of m!

I got to know about this from a test case which failed due to this exact reason.

Also, I have removed unused i.

![image.png](https://files.reviewableusercontent.io/images/reviewable/41180869/akIh3vn-aqUeC-U7LrDnwK3-/image.png)


<!-- Sent from Reviewable.io -->

2024-01-30 18:29 UTC, enitrat requested changes
> Reviewed 3 of 5 files at r12.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 16 of 19 files reviewed, 14 unresolved discussions (waiting on @bajpai244 and @ClementWalter)

___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 277 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKS-T49AKwBNeNuviR:-NpQ_TDU4-JyS0lNVmuc:b41bpwt) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L277)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

They aren't strictly equivalent.

shr: You panic if the shift is more than the bit size of the type { can be observed in rust, and i have added a comment explaining the same }
wrapping_shr: the shift can be greater than the bit size of the type  

I have replaced warpping_shr at shr wherever there is no possibility on panic.
</blockquote></details>

ok interesting: shr panics but only in rust. I was actually using python as a base - and even logically speaking: if you shift 0 one bit to the right, it stays a 0. 

But if the shift is greater than the byte size it panics! Sorry
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 330 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJwtSUCC0gDio-sp72:-NpQadRSC1ISjt7lEiqk:b139nvg) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L330)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

can u elaborate on this? Where does mask's involvement comes here?
</blockquote></details>

mask = 1 << (i-1)
which is similar to: `mask = 2**(i) -1`

`q = 1 << i-1`
<=> `q = 2**(i-1)`

thus:
`mask = (2 *q)  - 1` <=> `q = (mask+1)/2`
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 523 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJt5RT6mIM7SLsbOKS:-NpQbLH34mMz3mN5gHna:bhpyhqf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L523)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

But, that means we need wrapping! Because in our case shr will panic if the shift is more than BitSize of the type!

I will keep it here, as I remember there was a test which failed exactly because of this.
</blockquote></details>

yep sounds good, sorry thought that shr would always yield 0 when shifting more than the type size
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 60 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKTkY69ITZwvoyH4Vl:-NpQbX4QDUVXZMhYEy5i:b4b7fb7) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L60)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

So, the initial zeroes here have value! As the representation is little endian! So all early zeroes are  not ignorable.
</blockquote></details>

can you demonstrate exactly the process that happens here with an example in comment ? I don't understand well it seems
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 184 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKfcE3ClTx6XNDHhIq:-NpQbg3e34ACA5nuWL9R:b2zx8cy) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L184)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

Nope! the value of j is m, if we look at the range correctly, it has ..=, which means it is inclusive of m!

I got to know about this from a test case which failed due to this exact reason.

Also, I have removed unused i.

![image.png](https://files.reviewableusercontent.io/images/reviewable/41180869/akIh3vn-aqUeC-U7LrDnwK3-/image.png)
</blockquote></details>

oh sorry! didnt see the = before the m !


<!-- Sent from Reviewable.io -->

2024-01-31 12:58 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 14 of 20 files reviewed, 14 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/checked_math.cairo` line 130 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJc_el91Z-0GjcPvra:-NpUZeXq7MSu-MY5PCVJ:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/checked_math.cairo#L130)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Add to CheckedMath trait
</blockquote></details>

done
___
*[`crates/utils/src/checked_math.cairo` line 149 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJccmcDzynNhqQyLvX:-NpUZfDB0JYtFy-NFGFF:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/checked_math.cairo#L149)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

so that you can access it through CheckedMath only
</blockquote></details>

done
___
*[`crates/utils/src/crypto/modexp/arith.cairo` line 330 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpJwtSUCC0gDio-sp72:-NpUV7f02qjKoRNF3Aaj:bf873eb) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/arith.cairo#L330)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

mask = 1 << (i-1)
which is similar to: `mask = 2**(i) -1`

`q = 1 << i-1`
<=> `q = 2**(i-1)`

thus:
`mask = (2 *q)  - 1` <=> `q = (mask+1)/2`
</blockquote></details>

Brilliant! Done
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 60 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKTkY69ITZwvoyH4Vl:-NpU_Z7k5bY7HKGgfr4C:b5kcjx6) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L60)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

can you demonstrate exactly the process that happens here with an example in comment ? I don't understand well it seems
</blockquote></details>

Sure, in the below code, the slice `bytes.slice(0, r)` is inserted `buf` from index `WORD_BYTES  - r`, all words befored `WORD_BYTES -r` are set to 0.

Since buf is in little endia, it means all those zeros before `WORD_BYTES -r` have value, and hence we are not simply converting bytes.slice(0, r) to a number!
 
![image.png](https://files.reviewableusercontent.io/images/reviewable/41180869/RPZC5SP_15zU05VEB7iFmfCO/image.png)


<!-- Sent from Reviewable.io -->

2024-01-31 15:45 UTC, enitrat requested changes
LGTM! just add one last comments so that we don't forget to get back on some parts in the future.

> Reviewed 1 of 19 files at r1, 1 of 5 files at r12, 4 of 4 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-:-NpVBSSdDLfowpxHm9L-:b-ptbpe5)* status: all files reviewed, 7 unresolved discussions (waiting on @bajpai244 and @ClementWalter)

___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 60 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKTkY69ITZwvoyH4Vl:-NpV9x365I0mAxIeLJmK:b-s622lo) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L60)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

Sure, in the below code, the slice `bytes.slice(0, r)` is inserted `buf` from index `WORD_BYTES  - r`, all words befored `WORD_BYTES -r` are set to 0.

Since buf is in little endia, it means all those zeros before `WORD_BYTES -r` have value, and hence we are not simply converting bytes.slice(0, r) to a number!
 
![image.png](https://files.reviewableusercontent.io/images/reviewable/41180869/RPZC5SP_15zU05VEB7iFmfCO/image.png)
</blockquote></details>

I see, thanks
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 85 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKXtXH2XUkKwQd4DZf:-NpV9nEE8kga5MjwRmF8:b-ysfe1a) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L85)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

So, buffer can hold some value here before entering this condition if the r!=0 case is true! So, I won't remove it, as it can hold some value previously which can lie beyond len next_j
</blockquote></details>

Ok, let's add TODO: optimize on this because for example there is a useless conversion of Vec<u8> -> Span<u8> -> u64. 
If we can avoid these clones we can save a lot of step, if we don't mark it we will forget :thumbsup: 
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 217 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKhTL39_aR7LcbOvcp:-NpVAJd003ZW2abmolGL:b467o0z) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L217)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

It does right? a is in place changed by the function before it, and the result is then applied to self.digits
</blockquote></details>

Ok got it!
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 351 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpVAVbBBnhF2bxgeBi2:-NpVAVbBBnhF2bxgeBi3:bt0i0c0) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L351)):*
> ```Cairo
>         //
>         // The case of modulus being 0 should have already been
>         // handled in modexp().
> ```

think we can keep this one



_Code quote:_
```Cairo
        // base^0 is always 1, regardless of base.
        // Hence the result is 0 for (base^0) % 1, and 1
        // for every modulus larger than 1.
        //
        // The case of modulus being 0 should have already been
        // handled in modexp().
```
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 590 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKws291r6ojMYhVXAk:-NpVBKHn9CYQ76WKzSBO:b-rij06u) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L590)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

done
</blockquote></details>

not seeing it
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 599 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKwyTmBFbDkfW7b3G0:-NpVBMAHAJA0bzufBYDH:b-rij06u) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L599)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

done
</blockquote></details>

not seeing it
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 677 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKy-K52E50ioAWtqXW:-NpVBNAO0bfHHaiVeHUZ:b-rij06u) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L677)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

done
</blockquote></details>

not seeing it


<!-- Sent from Reviewable.io -->

2024-01-31 15:52 UTC, bajpai244 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: all files reviewed, 7 unresolved discussions (waiting on @ClementWalter and @enitrat)

___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 85 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKXtXH2XUkKwQd4DZf:-NpVC-S7-Cy9c3Ao4iSb:bb6un1j) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L85)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Ok, let's add TODO: optimize on this because for example there is a useless conversion of Vec<u8> -> Span<u8> -> u64. 
If we can avoid these clones we can save a lot of step, if we don't mark it we will forget :thumbsup:
</blockquote></details>

Done
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 351 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpVAVbBBnhF2bxgeBi2:-NpVCCzI8IsMBGH2iEpr:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L351)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

think we can keep this one
</blockquote></details>

done
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 590 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKws291r6ojMYhVXAk:-NpVCbIRDL4r1yXtXa53:b-moxrhj) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L590)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

not seeing it
</blockquote></details>

Look like missed it, done
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 599 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKwyTmBFbDkfW7b3G0:-NpVCyWd8mKjdEBgensK:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L599)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

not seeing it
</blockquote></details>

done
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 677 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKy-K52E50ioAWtqXW:-NpVDEbtB3h_z402efGV:bb7f2mf) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L677)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

not seeing it
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-02-05 09:16 UTC, enitrat requested changes
> Reviewed 8 of 8 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: all files reviewed, 2 unresolved discussions (waiting on @bajpai244 and @ClementWalter)

___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 85 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKXtXH2XUkKwQd4DZf:-NpsYLiq8OH9KtfjUnjZ:bf9dz6c) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L85)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Not seeing the todo
___
*[`crates/utils/src/crypto/modexp/mpnat.cairo` line 677 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-NpKy-K52E50ioAWtqXW:-NpsYPxu5O6E0Mmxwut3:b-6bix3e) ([raw file](https://github.com/kkrt-labs/kakarot-ssj/blob/38305c189b94f5eebbde3ed8c1aa1418eb800c85/crates/utils/src/crypto/modexp/mpnat.cairo#L677)):*
<details><summary><i>Previously, bajpai244 (Harsh Bajpai) wrote…</i></summary><blockquote>

done
</blockquote></details>

still not


<!-- Sent from Reviewable.io -->

2024-02-05 09:42 UTC, enitrat reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)* status: 20 of 21 files reviewed, 1 unresolved discussion (waiting on @bajpai244 and @ClementWalter)



<!-- Sent from Reviewable.io -->

2024-02-05 09:42 UTC, enitrat approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718#-:-NpsdOPL8e4lZJsYSoct:bnfp4nl)* status: 20 of 21 files reviewed, all discussions resolved (waiting on @ClementWalter)



<!-- Sent from Reviewable.io -->

2024-02-05 09:42 UTC, merged