Add constants for precompiles addresses range.
kkrt-labs/kakarot-ssj pull request #868
Opened 2024-08-23 15:55 UTC by lprovenzano

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

- I have changed the magic numbers to constants.
- Refactor in `is_precompile()` for better cohesion of comparisons.
- Added unit tests to make sure it behaves as it should.

## What is the new behavior?

It does not change the behavior, it adds better readability.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2024-08-23 16:11 UTC, enitrat commented on crates/evm/src/model.cairo
> +        let equal_than_max: bool = self.into() == MAX_PRECOMPILE_ADDRESS;
no need for extra variables, just inline the comparisons

2024-08-23 16:17 UTC, enitrat requested changes

2024-08-23 16:17 UTC, enitrat commented on crates/evm/src/model.cairo
> +const MAX_PRECOMPILE_ADDRESS: u256 = 256;
prefer hexadecimal
also: a better name would be the one from the reference.
```suggestion
const FIRST_ROLLUP_PRECOMPILE_ADDRESS: u256 = 0x100;
```

2024-08-23 16:17 UTC, enitrat commented on crates/evm/src/model.cairo
> +const LIMIT_PRECOMPILE_ADDRESS: u256 = 10;
```suggestion
const LIMIT_PRECOMPILE_ADDRESS: u256 = 0x0a;
```

2024-08-23 16:17 UTC, enitrat commented on crates/evm/src/model.cairo
> +       let evm_address: EthAddress = 5.try_into().unwrap();
you could create a single test with all the valid precompiles in an array and ensure that, for each address, it's valid.

```suggestion
   let valid_precompiles = [0x1,0x2,0x3,0x4,0x5,0x6,0x7,0x8,0x9,0xa,0x100];
   for address in valid_precompiles {
      assert!((*address).try_into().unwrap().is_precompile());
     }
  ```
  
  (syntax to verify)
  
  This avoid creating a lot of tests that don't have extensive coverage and take some time to setup and run
```

2024-08-23 16:17 UTC, enitrat commented on crates/evm/src/model.cairo
> +       assert_eq!(true, is_precompile, "expected: {:?}, got: {:?}", true, is_precompile);
just for your knowledge, you don't have to add the "expected ... got ..." string, assert_eq! handles this automatically

2024-08-23 23:15 UTC, lprovenzano commented
Done changes @enitrat.

2024-08-24 07:53 UTC, enitrat commented on crates/evm/src/model.cairo
> +       loop {
use a `for` loop instead https://book.cairo-lang.org/ch02-05-control-flow.html?highlight=for%20loop#looping-through-a-collection-with-for

2024-08-24 17:09 UTC, lprovenzano commented on crates/evm/src/model.cairo
> +       loop {
Done.

2024-08-25 18:03 UTC, enitrat approved these changes

2024-08-25 18:03 UTC, merged